-- phpMyAdmin SQL Dump
-- version 4.3.11
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Jul 27, 2015 at 01:57 PM
-- Server version: 5.6.24
-- PHP Version: 5.6.8

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `wp_realestate`
--

-- --------------------------------------------------------

--
-- Table structure for table `wp_commentmeta`
--

CREATE TABLE IF NOT EXISTS `wp_commentmeta` (
  `meta_id` bigint(20) unsigned NOT NULL,
  `comment_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `meta_key` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `meta_value` longtext COLLATE utf8mb4_unicode_ci
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `wp_comments`
--

CREATE TABLE IF NOT EXISTS `wp_comments` (
  `comment_ID` bigint(20) unsigned NOT NULL,
  `comment_post_ID` bigint(20) unsigned NOT NULL DEFAULT '0',
  `comment_author` tinytext COLLATE utf8mb4_unicode_ci NOT NULL,
  `comment_author_email` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `comment_author_url` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `comment_author_IP` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `comment_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `comment_date_gmt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `comment_content` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `comment_karma` int(11) NOT NULL DEFAULT '0',
  `comment_approved` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '1',
  `comment_agent` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `comment_type` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `comment_parent` bigint(20) unsigned NOT NULL DEFAULT '0',
  `user_id` bigint(20) unsigned NOT NULL DEFAULT '0'
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `wp_comments`
--

INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES
(1, 1, 'Mr WordPress', '', 'https://wordpress.org/', '', '2015-07-22 19:54:48', '2015-07-22 19:54:48', 'Hi, this is a comment.\nTo delete a comment, just log in and view the post&#039;s comments. There you will have the option to edit or delete them.', 0, '1', '', '', 0, 0);

-- --------------------------------------------------------

--
-- Table structure for table `wp_eg_attachments_clicks`
--

CREATE TABLE IF NOT EXISTS `wp_eg_attachments_clicks` (
  `click_id` bigint(20) NOT NULL,
  `click_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `attach_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `attach_title` text NOT NULL,
  `post_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `post_title` text NOT NULL,
  `clicks_number` int(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- --------------------------------------------------------

--
-- Table structure for table `wp_huge_itslider_images`
--

CREATE TABLE IF NOT EXISTS `wp_huge_itslider_images` (
  `id` int(11) unsigned NOT NULL,
  `name` varchar(100) DEFAULT NULL,
  `slider_id` varchar(200) DEFAULT NULL,
  `description` text,
  `image_url` text,
  `sl_url` varchar(128) DEFAULT NULL,
  `sl_type` text NOT NULL,
  `link_target` text NOT NULL,
  `sl_stitle` text NOT NULL,
  `sl_sdesc` text NOT NULL,
  `sl_postlink` text NOT NULL,
  `ordering` int(11) NOT NULL,
  `published` tinyint(4) unsigned DEFAULT NULL,
  `published_in_sl_width` tinyint(4) unsigned DEFAULT NULL
) ENGINE=MyISAM AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;

--
-- Dumping data for table `wp_huge_itslider_images`
--

INSERT INTO `wp_huge_itslider_images` (`id`, `name`, `slider_id`, `description`, `image_url`, `sl_url`, `sl_type`, `link_target`, `sl_stitle`, `sl_sdesc`, `sl_postlink`, `ordering`, `published`, `published_in_sl_width`) VALUES
(1, '', '1', '', 'http://localhost/pre/wp-content/plugins/slider-image/Front_images/slides/slide1.jpg', 'http://huge-it.com', 'image', 'on', '', '', '', 1, 1, NULL),
(2, 'Simple Usage', '1', '', 'http://localhost/pre/wp-content/plugins/slider-image/Front_images/slides/slide2.jpg', 'http://huge-it.com', 'image', 'on', '', '', '', 2, 1, NULL),
(3, 'Huge-IT Slider', '1', 'The slider allows having unlimited amount of images with their titles and descriptions. The slider uses autogenerated shortcodes making it easier for the users to add it to the custom location.', 'http://localhost/pre/wp-content/plugins/slider-image/Front_images/slides/slide3.jpg', 'http://huge-it.com', 'image', 'on', '', '', '', 3, 1, NULL);

-- --------------------------------------------------------

--
-- Table structure for table `wp_huge_itslider_params`
--

CREATE TABLE IF NOT EXISTS `wp_huge_itslider_params` (
  `id` int(11) unsigned NOT NULL,
  `name` varchar(50) CHARACTER SET utf8 NOT NULL,
  `title` varchar(200) CHARACTER SET utf8 NOT NULL,
  `description` text CHARACTER SET utf8 NOT NULL,
  `value` varchar(200) CHARACTER SET utf8 NOT NULL
) ENGINE=MyISAM AUTO_INCREMENT=127 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `wp_huge_itslider_params`
--

INSERT INTO `wp_huge_itslider_params` (`id`, `name`, `title`, `description`, `value`) VALUES
(89, 'slider_crop_image', 'Slider crop image', 'Slider crop image', 'resize'),
(90, 'slider_title_color', 'Slider title color', 'Slider title color', '000000'),
(91, 'slider_title_font_size', 'Slider title font size', 'Slider title font size', '13'),
(92, 'slider_description_color', 'Slider description color', 'Slider description color', 'ffffff'),
(93, 'slider_description_font_size', 'Slider description font size', 'Slider description font size', '13'),
(94, 'slider_title_position', 'Slider title position', 'Slider title position', 'right-top'),
(95, 'slider_description_position', 'Slider description position', 'Slider description position', 'right-bottom'),
(96, 'slider_title_border_size', 'Slider Title border size', 'Slider Title border size', '0'),
(97, 'slider_title_border_color', 'Slider title border color', 'Slider title border color', 'ffffff'),
(98, 'slider_title_border_radius', 'Slider title border radius', 'Slider title border radius', '4'),
(99, 'slider_description_border_size', 'Slider description border size', 'Slider description border size', '0'),
(100, 'slider_description_border_color', 'Slider description border color', 'Slider description border color', 'ffffff'),
(101, 'slider_description_border_radius', 'Slider description border radius', 'Slider description border radius', '0'),
(102, 'slider_slideshow_border_size', 'Slider border size', 'Slider border size', '0'),
(103, 'slider_slideshow_border_color', 'Slider border color', 'Slider border color', 'ffffff'),
(104, 'slider_slideshow_border_radius', 'Slider border radius', 'Slider border radius', '0'),
(105, 'slider_navigation_type', 'Slider navigation type', 'Slider navigation type', '1'),
(106, 'slider_navigation_position', 'Slider navigation position', 'Slider navigation position', 'bottom'),
(107, 'slider_title_background_color', 'Slider title background color', 'Slider title background color', 'ffffff'),
(108, 'slider_description_background_color', 'Slider description background color', 'Slider description background color', '000000'),
(109, 'slider_title_transparent', 'Slider title has background', 'Slider title has background', 'on'),
(110, 'slider_description_transparent', 'Slider description has background', 'Slider description has background', 'on'),
(111, 'slider_slider_background_color', 'Slider slider background color', 'Slider slider background color', 'ffffff'),
(112, 'slider_dots_position', 'slider dots position', 'slider dots position', 'top'),
(113, 'slider_active_dot_color', 'slider active dot color', '', 'ffffff'),
(114, 'slider_dots_color', 'slider dots color', '', '000000'),
(115, 'slider_description_width', 'Slider description width', 'Slider description width', '70'),
(116, 'slider_description_height', 'Slider description height', 'Slider description height', '50'),
(117, 'slider_description_background_transparency', 'slider description background transparency', 'slider description background transparency', '70'),
(118, 'slider_description_text_align', 'description text-align', 'description text-align', 'justify'),
(119, 'slider_title_width', 'slider title width', 'slider title width', '30'),
(120, 'slider_title_height', 'slider title height', 'slider title height', '50'),
(121, 'slider_title_background_transparency', 'slider title background transparency', 'slider title background transparency', '70'),
(122, 'slider_title_text_align', 'title text-align', 'title text-align', 'right'),
(123, 'slider_title_has_margin', 'title has margin', 'title has margin', 'on'),
(124, 'slider_description_has_margin', 'description has margin', 'description has margin', 'on'),
(125, 'slider_show_arrows', 'Slider show left right arrows', 'Slider show left right arrows', 'on'),
(126, 'loading_icon_type', 'Slider loading icon type', 'Slider loading icon type', '1');

-- --------------------------------------------------------

--
-- Table structure for table `wp_huge_itslider_sliders`
--

CREATE TABLE IF NOT EXISTS `wp_huge_itslider_sliders` (
  `id` int(11) unsigned NOT NULL,
  `name` varchar(200) NOT NULL,
  `sl_height` int(11) unsigned DEFAULT NULL,
  `sl_width` int(11) unsigned DEFAULT NULL,
  `pause_on_hover` text,
  `slider_list_effects_s` text,
  `description` text,
  `param` text,
  `sl_position` text NOT NULL,
  `ordering` int(11) NOT NULL,
  `published` text,
  `sl_loading_icon` text NOT NULL
) ENGINE=MyISAM AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

--
-- Dumping data for table `wp_huge_itslider_sliders`
--

INSERT INTO `wp_huge_itslider_sliders` (`id`, `name`, `sl_height`, `sl_width`, `pause_on_hover`, `slider_list_effects_s`, `description`, `param`, `sl_position`, `ordering`, `published`, `sl_loading_icon`) VALUES
(1, 'My First Slider', 375, 600, 'on', 'random', '4000', '1000', 'center', 1, '300', '');

-- --------------------------------------------------------

--
-- Table structure for table `wp_links`
--

CREATE TABLE IF NOT EXISTS `wp_links` (
  `link_id` bigint(20) unsigned NOT NULL,
  `link_url` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `link_name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `link_image` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `link_target` varchar(25) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `link_description` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `link_visible` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'Y',
  `link_owner` bigint(20) unsigned NOT NULL DEFAULT '1',
  `link_rating` int(11) NOT NULL DEFAULT '0',
  `link_updated` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `link_rel` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `link_notes` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `link_rss` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `wp_masterslider_options`
--

CREATE TABLE IF NOT EXISTS `wp_masterslider_options` (
  `ID` smallint(5) unsigned NOT NULL,
  `option_name` varchar(120) COLLATE utf8mb4_unicode_ci NOT NULL,
  `option_value` text COLLATE utf8mb4_unicode_ci NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `wp_masterslider_options`
--

INSERT INTO `wp_masterslider_options` (`ID`, `option_name`, `option_value`) VALUES
(1, 'masterslider_custom_css_ver', '1.6');

-- --------------------------------------------------------

--
-- Table structure for table `wp_masterslider_sliders`
--

CREATE TABLE IF NOT EXISTS `wp_masterslider_sliders` (
  `ID` mediumint(8) unsigned NOT NULL,
  `title` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `type` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,
  `slides_num` smallint(5) unsigned NOT NULL,
  `date_created` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `date_modified` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `params` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `custom_styles` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `custom_fonts` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `status` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'draft'
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `wp_masterslider_sliders`
--

INSERT INTO `wp_masterslider_sliders` (`ID`, `title`, `type`, `slides_num`, `date_created`, `date_modified`, `params`, `custom_styles`, `custom_fonts`, `status`) VALUES
(1, 'Sample slider', 'custom', 10, '2015-07-27 10:58:26', '2015-07-27 11:36:03', 'eyJtZXRhIjp7IlNldHRpbmdzIWlkcyI6IjEiLCJTZXR0aW5ncyFuZXh0SWQiOjIsIlNsaWRlIWlkcyI6IjEsMiwzLDQsNSw2LDcsOSwxMiwxNCIsIlNsaWRlIW5leHRJZCI6MTUsIkNvbnRyb2whaWRzIjoiMSwyLDMiLCJDb250cm9sIW5leHRJZCI6Nn0sIk1TUGFuZWwuU2V0dGluZ3MiOnsiMSI6IntcImlkXCI6XCIxXCIsXCJzbmFwcGluZ1wiOnRydWUsXCJkaXNhYmxlQ29udHJvbHNcIjpmYWxzZSxcIm5hbWVcIjpcIlNhbXBsZSBzbGlkZXJcIixcIndpZHRoXCI6ODAwLFwiaGVpZ2h0XCI6NDgwLFwid3JhcHBlcldpZHRoXCI6ODAwLFwid3JhcHBlcldpZHRoVW5pdFwiOlwicHhcIixcImF1dG9Dcm9wXCI6ZmFsc2UsXCJ0eXBlXCI6XCJjdXN0b21cIixcInNsaWRlcklkXCI6XCIxXCIsXCJsYXlvdXRcIjpcImJveGVkXCIsXCJhdXRvSGVpZ2h0XCI6ZmFsc2UsXCJ0clZpZXdcIjpcImJhc2ljXCIsXCJzcGVlZFwiOjIwLFwic3BhY2VcIjowLFwic3RhcnRcIjoxLFwiZ3JhYkN1cnNvclwiOnRydWUsXCJzd2lwZVwiOnRydWUsXCJtb3VzZVwiOnRydWUsXCJ3aGVlbFwiOmZhbHNlLFwiYXV0b3BsYXlcIjp0cnVlLFwibG9vcFwiOnRydWUsXCJzaHVmZmxlXCI6ZmFsc2UsXCJwcmVsb2FkXCI6XCItMVwiLFwib3ZlclBhdXNlXCI6dHJ1ZSxcImVuZFBhdXNlXCI6ZmFsc2UsXCJoaWRlTGF5ZXJzXCI6ZmFsc2UsXCJkaXJcIjpcImhcIixcInBhcmFsbGF4TW9kZVwiOlwic3dpcGVcIixcInVzZURlZXBMaW5rXCI6ZmFsc2UsXCJkZWVwTGlua1R5cGVcIjpcInBhdGhcIixcInNjcm9sbFBhcmFsbGF4TW92ZVwiOjMwLFwic2Nyb2xsUGFyYWxsYXhCR01vdmVcIjo1MCxcInNjcm9sbFBhcmFsbGF4RmFkZVwiOnRydWUsXCJjZW50ZXJDb250cm9sc1wiOnRydWUsXCJpbnN0YW50U2hvd0xheWVyc1wiOmZhbHNlLFwiY2xhc3NOYW1lXCI6XCJcIixcImJnQ29sb3JcIjpcIiMwMDAwMDBcIixcInNraW5cIjpcIm1zLXNraW4tbGlnaHQtMlwiLFwibXNUZW1wbGF0ZVwiOlwiY3VzdG9tXCIsXCJtc1RlbXBsYXRlQ2xhc3NcIjpcIlwiLFwidXNlZEZvbnRzXCI6XCJcIn0ifSwiTVNQYW5lbC5TbGlkZSI6eyIxIjoie1wiaWRcIjpcIjFcIixcInRpbWVsaW5lX2hcIjoyMDAsXCJiZ1RodW1iXCI6XCIvMjAxMi8xMC8xMjEtMTUweDE1MC5qcGdcIixcIm9yZGVyXCI6MCxcImlzaGlkZVwiOmZhbHNlLFwiYmdcIjpcIi8yMDEyLzEwLzEyMS5qcGdcIixcImR1cmF0aW9uXCI6MyxcImZpbGxNb2RlXCI6XCJmaWxsXCIsXCJiZ3ZfZmlsbG1vZGVcIjpcImZpbGxcIixcImJndl9sb29wXCI6dHJ1ZSxcImJndl9tdXRlXCI6dHJ1ZSxcImJndl9hdXRvcGF1c2VcIjpmYWxzZSxcImxheWVyX2lkc1wiOltdfSIsIjIiOiJ7XCJpZFwiOjIsXCJ0aW1lbGluZV9oXCI6MjAwLFwiYmdUaHVtYlwiOlwiLzIwMTIvMTAvMi0xNTB4MTUwLmpwZ1wiLFwib3JkZXJcIjoxLFwiYmdcIjpcIi8yMDEyLzEwLzIuanBnXCIsXCJkdXJhdGlvblwiOjMsXCJmaWxsTW9kZVwiOlwiZmlsbFwiLFwiYmd2X2ZpbGxtb2RlXCI6XCJmaWxsXCIsXCJiZ3ZfbG9vcFwiOnRydWUsXCJiZ3ZfbXV0ZVwiOnRydWUsXCJiZ3ZfYXV0b3BhdXNlXCI6ZmFsc2UsXCJsYXllcl9pZHNcIjpbXX0iLCIzIjoie1wiaWRcIjozLFwidGltZWxpbmVfaFwiOjIwMCxcImJnVGh1bWJcIjpcIi8yMDEyLzEwLzExLTE1MHgxNTAuanBnXCIsXCJvcmRlclwiOjIsXCJiZ1wiOlwiLzIwMTIvMTAvMTEuanBnXCIsXCJkdXJhdGlvblwiOjMsXCJmaWxsTW9kZVwiOlwiZmlsbFwiLFwiYmd2X2ZpbGxtb2RlXCI6XCJmaWxsXCIsXCJiZ3ZfbG9vcFwiOnRydWUsXCJiZ3ZfbXV0ZVwiOnRydWUsXCJiZ3ZfYXV0b3BhdXNlXCI6ZmFsc2UsXCJsYXllcl9pZHNcIjpbXX0iLCI0Ijoie1wiaWRcIjo0LFwidGltZWxpbmVfaFwiOjIwMCxcImJnVGh1bWJcIjpcIi8yMDEyLzEwLzMtMTUweDE1MC5qcGdcIixcIm9yZGVyXCI6MyxcImJnXCI6XCIvMjAxMi8xMC8zLmpwZ1wiLFwiZHVyYXRpb25cIjozLFwiZmlsbE1vZGVcIjpcImZpbGxcIixcImJndl9maWxsbW9kZVwiOlwiZmlsbFwiLFwiYmd2X2xvb3BcIjp0cnVlLFwiYmd2X211dGVcIjp0cnVlLFwiYmd2X2F1dG9wYXVzZVwiOmZhbHNlLFwibGF5ZXJfaWRzXCI6W119IiwiNSI6IntcImlkXCI6NSxcInRpbWVsaW5lX2hcIjoyMDAsXCJiZ1RodW1iXCI6XCIvMjAxMi8xMC85LTE1MHgxNTAuanBnXCIsXCJvcmRlclwiOjQsXCJiZ1wiOlwiLzIwMTIvMTAvOS5qcGdcIixcImR1cmF0aW9uXCI6MyxcImZpbGxNb2RlXCI6XCJmaWxsXCIsXCJiZ3ZfZmlsbG1vZGVcIjpcImZpbGxcIixcImJndl9sb29wXCI6dHJ1ZSxcImJndl9tdXRlXCI6dHJ1ZSxcImJndl9hdXRvcGF1c2VcIjpmYWxzZSxcImxheWVyX2lkc1wiOltdfSIsIjYiOiJ7XCJpZFwiOjYsXCJ0aW1lbGluZV9oXCI6MjAwLFwiYmdUaHVtYlwiOlwiLzIwMTIvMTAvOC0xNTB4MTUwLmpwZ1wiLFwib3JkZXJcIjo1LFwiYmdcIjpcIi8yMDEyLzEwLzguanBnXCIsXCJkdXJhdGlvblwiOjMsXCJmaWxsTW9kZVwiOlwiZmlsbFwiLFwiYmd2X2ZpbGxtb2RlXCI6XCJmaWxsXCIsXCJiZ3ZfbG9vcFwiOnRydWUsXCJiZ3ZfbXV0ZVwiOnRydWUsXCJiZ3ZfYXV0b3BhdXNlXCI6ZmFsc2UsXCJsYXllcl9pZHNcIjpbXX0iLCI3Ijoie1wiaWRcIjo3LFwidGltZWxpbmVfaFwiOjIwMCxcImJnVGh1bWJcIjpcIi8yMDEyLzEwLzQtMTUweDE1MC5qcGdcIixcIm9yZGVyXCI6NixcImJnXCI6XCIvMjAxMi8xMC80LmpwZ1wiLFwiZHVyYXRpb25cIjozLFwiZmlsbE1vZGVcIjpcImZpbGxcIixcImJndl9maWxsbW9kZVwiOlwiZmlsbFwiLFwiYmd2X2xvb3BcIjp0cnVlLFwiYmd2X211dGVcIjp0cnVlLFwiYmd2X2F1dG9wYXVzZVwiOmZhbHNlLFwibGF5ZXJfaWRzXCI6W119IiwiOSI6IntcImlkXCI6OSxcInRpbWVsaW5lX2hcIjoyMDAsXCJiZ1RodW1iXCI6XCIvMjAxMi8xMC8xMy0xNTB4MTUwLmpwZ1wiLFwib3JkZXJcIjo3LFwiYmdcIjpcIi8yMDEyLzEwLzEzLmpwZ1wiLFwiZHVyYXRpb25cIjozLFwiZmlsbE1vZGVcIjpcImZpbGxcIixcImJndl9maWxsbW9kZVwiOlwiZmlsbFwiLFwiYmd2X2xvb3BcIjp0cnVlLFwiYmd2X211dGVcIjp0cnVlLFwiYmd2X2F1dG9wYXVzZVwiOmZhbHNlLFwibGF5ZXJfaWRzXCI6W119IiwiMTIiOiJ7XCJpZFwiOjEyLFwidGltZWxpbmVfaFwiOjIwMCxcImJnVGh1bWJcIjpcIi8yMDEyLzEwLzE2LTE1MHgxNTAuanBnXCIsXCJvcmRlclwiOjgsXCJiZ1wiOlwiLzIwMTIvMTAvMTYuanBnXCIsXCJkdXJhdGlvblwiOjMsXCJmaWxsTW9kZVwiOlwiZmlsbFwiLFwiYmd2X2ZpbGxtb2RlXCI6XCJmaWxsXCIsXCJiZ3ZfbG9vcFwiOnRydWUsXCJiZ3ZfbXV0ZVwiOnRydWUsXCJiZ3ZfYXV0b3BhdXNlXCI6ZmFsc2UsXCJsYXllcl9pZHNcIjpbXX0iLCIxNCI6IntcImlkXCI6MTQsXCJ0aW1lbGluZV9oXCI6MjAwLFwiYmdUaHVtYlwiOlwiLzIwMTIvMTAvMTUxLTE1MHgxNTAuanBnXCIsXCJvcmRlclwiOjksXCJiZ1wiOlwiLzIwMTIvMTAvMTUxLmpwZ1wiLFwiZHVyYXRpb25cIjozLFwiZmlsbE1vZGVcIjpcImZpbGxcIixcImJndl9maWxsbW9kZVwiOlwiZmlsbFwiLFwiYmd2X2xvb3BcIjp0cnVlLFwiYmd2X211dGVcIjp0cnVlLFwiYmd2X2F1dG9wYXVzZVwiOmZhbHNlLFwibGF5ZXJfaWRzXCI6W119In0sIk1TUGFuZWwuQ29udHJvbCI6eyIxIjoie1wiaWRcIjpcIjFcIixcImxhYmVsXCI6XCJBcnJvd3NcIixcIm5hbWVcIjpcImFycm93c1wiLFwiYXV0b0hpZGVcIjpmYWxzZSxcIm92ZXJWaWRlb1wiOnRydWUsXCJpbnNldFwiOnRydWV9IiwiMiI6IntcImlkXCI6MixcImxhYmVsXCI6XCJCdWxsZXRzXCIsXCJuYW1lXCI6XCJidWxsZXRzXCIsXCJhdXRvSGlkZVwiOmZhbHNlLFwib3ZlclZpZGVvXCI6dHJ1ZSxcIm1hcmdpblwiOjEwLFwiZGlyXCI6XCJoXCIsXCJhbGlnblwiOlwiYm90dG9tXCIsXCJpbnNldFwiOnRydWV9IiwiMyI6IntcImlkXCI6MyxcImxhYmVsXCI6XCJUaHVtYmxpc3QvVGFic1wiLFwibmFtZVwiOlwidGh1bWJsaXN0XCIsXCJhdXRvSGlkZVwiOmZhbHNlLFwib3ZlclZpZGVvXCI6dHJ1ZSxcIm1hcmdpblwiOjUsXCJzcGFjZVwiOjUsXCJ3aWR0aFwiOjE0MCxcImhlaWdodFwiOjgwLFwiYWxpZ25cIjpcImJvdHRvbVwiLFwiaW5zZXRcIjpmYWxzZSxcImZpbGxNb2RlXCI6XCJmaWxsXCJ9In19', '', '', 'published');

-- --------------------------------------------------------

--
-- Table structure for table `wp_options`
--

CREATE TABLE IF NOT EXISTS `wp_options` (
  `option_id` bigint(20) unsigned NOT NULL,
  `option_name` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `option_value` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `autoload` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'yes'
) ENGINE=InnoDB AUTO_INCREMENT=275 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `wp_options`
--

INSERT INTO `wp_options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES
(1, 'siteurl', 'http://localhost/pre', 'yes'),
(2, 'home', 'http://localhost/pre', 'yes'),
(3, 'blogname', 'Real Estate', 'yes'),
(4, 'blogdescription', 'Just another WordPress site', 'yes'),
(5, 'users_can_register', '0', 'yes'),
(6, 'admin_email', 'lunardrik@gmail.com', 'yes'),
(7, 'start_of_week', '1', 'yes'),
(8, 'use_balanceTags', '0', 'yes'),
(9, 'use_smilies', '1', 'yes'),
(10, 'require_name_email', '1', 'yes'),
(11, 'comments_notify', '1', 'yes'),
(12, 'posts_per_rss', '10', 'yes'),
(13, 'rss_use_excerpt', '0', 'yes'),
(14, 'mailserver_url', 'mail.example.com', 'yes'),
(15, 'mailserver_login', 'login@example.com', 'yes'),
(16, 'mailserver_pass', 'password', 'yes'),
(17, 'mailserver_port', '110', 'yes'),
(18, 'default_category', '1', 'yes'),
(19, 'default_comment_status', 'open', 'yes'),
(20, 'default_ping_status', 'open', 'yes'),
(21, 'default_pingback_flag', '1', 'yes'),
(22, 'posts_per_page', '10', 'yes'),
(23, 'date_format', 'F j, Y', 'yes'),
(24, 'time_format', 'g:i a', 'yes'),
(25, 'links_updated_date_format', 'F j, Y g:i a', 'yes'),
(26, 'comment_moderation', '0', 'yes'),
(27, 'moderation_notify', '1', 'yes'),
(28, 'permalink_structure', '/%year%/%monthnum%/%day%/%postname%/', 'yes'),
(29, 'gzipcompression', '0', 'yes'),
(30, 'hack_file', '0', 'yes'),
(31, 'blog_charset', 'UTF-8', 'yes'),
(32, 'moderation_keys', '', 'no'),
(33, 'active_plugins', 'a:5:{i:0;s:41:"be-subpages-widget/be-subpages-widget.php";i:1;s:33:"eg-attachments/eg-attachments.php";i:2;s:37:"embed-google-map/embed_google_map.php";i:3;s:31:"master-slider/master-slider.php";i:4;s:23:"slider-image/slider.php";}', 'yes'),
(34, 'category_base', '', 'yes'),
(35, 'ping_sites', 'http://rpc.pingomatic.com/', 'yes'),
(36, 'advanced_edit', '0', 'yes'),
(37, 'comment_max_links', '2', 'yes'),
(38, 'gmt_offset', '0', 'yes'),
(39, 'default_email_category', '1', 'yes'),
(40, 'recently_edited', 'a:2:{i:0;s:103:"U:\\projects\\general\\tools\\xampp\\htdocs\\pre/wp-content/plugins/be-subpages-widget/be-subpages-widget.php";i:2;s:0:"";}', 'no'),
(41, 'template', 'building', 'yes'),
(42, 'stylesheet', 'building', 'yes'),
(43, 'comment_whitelist', '1', 'yes'),
(44, 'blacklist_keys', '', 'no'),
(45, 'comment_registration', '0', 'yes'),
(46, 'html_type', 'text/html', 'yes'),
(47, 'use_trackback', '0', 'yes'),
(48, 'default_role', 'subscriber', 'yes'),
(49, 'db_version', '31535', 'yes'),
(50, 'uploads_use_yearmonth_folders', '1', 'yes'),
(51, 'upload_path', '', 'yes'),
(52, 'blog_public', '1', 'yes'),
(53, 'default_link_category', '2', 'yes'),
(54, 'show_on_front', 'posts', 'yes'),
(55, 'tag_base', '', 'yes'),
(56, 'show_avatars', '1', 'yes'),
(57, 'avatar_rating', 'G', 'yes'),
(58, 'upload_url_path', '', 'yes'),
(59, 'thumbnail_size_w', '150', 'yes'),
(60, 'thumbnail_size_h', '150', 'yes'),
(61, 'thumbnail_crop', '1', 'yes'),
(62, 'medium_size_w', '300', 'yes'),
(63, 'medium_size_h', '300', 'yes'),
(64, 'avatar_default', 'mystery', 'yes'),
(65, 'large_size_w', '1024', 'yes'),
(66, 'large_size_h', '1024', 'yes'),
(67, 'image_default_link_type', 'file', 'yes'),
(68, 'image_default_size', '', 'yes'),
(69, 'image_default_align', '', 'yes'),
(70, 'close_comments_for_old_posts', '0', 'yes'),
(71, 'close_comments_days_old', '14', 'yes'),
(72, 'thread_comments', '1', 'yes'),
(73, 'thread_comments_depth', '5', 'yes'),
(74, 'page_comments', '0', 'yes'),
(75, 'comments_per_page', '50', 'yes'),
(76, 'default_comments_page', 'newest', 'yes'),
(77, 'comment_order', 'asc', 'yes'),
(78, 'sticky_posts', 'a:0:{}', 'yes'),
(79, 'widget_categories', 'a:2:{i:2;a:4:{s:5:"title";s:0:"";s:5:"count";i:0;s:12:"hierarchical";i:0;s:8:"dropdown";i:0;}s:12:"_multiwidget";i:1;}', 'yes'),
(80, 'widget_text', 'a:2:{i:1;a:0:{}s:12:"_multiwidget";i:1;}', 'yes'),
(81, 'widget_rss', 'a:2:{i:1;a:0:{}s:12:"_multiwidget";i:1;}', 'yes'),
(82, 'uninstall_plugins', 'a:0:{}', 'no'),
(83, 'timezone_string', '', 'yes'),
(84, 'page_for_posts', '0', 'yes'),
(85, 'page_on_front', '0', 'yes'),
(86, 'default_post_format', '0', 'yes'),
(87, 'link_manager_enabled', '0', 'yes'),
(88, 'initial_db_version', '31535', 'yes'),
(89, 'wp_user_roles', 'a:5:{s:13:"administrator";a:2:{s:4:"name";s:13:"Administrator";s:12:"capabilities";a:68:{s:13:"switch_themes";b:1;s:11:"edit_themes";b:1;s:16:"activate_plugins";b:1;s:12:"edit_plugins";b:1;s:10:"edit_users";b:1;s:10:"edit_files";b:1;s:14:"manage_options";b:1;s:17:"moderate_comments";b:1;s:17:"manage_categories";b:1;s:12:"manage_links";b:1;s:12:"upload_files";b:1;s:6:"import";b:1;s:15:"unfiltered_html";b:1;s:10:"edit_posts";b:1;s:17:"edit_others_posts";b:1;s:20:"edit_published_posts";b:1;s:13:"publish_posts";b:1;s:10:"edit_pages";b:1;s:4:"read";b:1;s:8:"level_10";b:1;s:7:"level_9";b:1;s:7:"level_8";b:1;s:7:"level_7";b:1;s:7:"level_6";b:1;s:7:"level_5";b:1;s:7:"level_4";b:1;s:7:"level_3";b:1;s:7:"level_2";b:1;s:7:"level_1";b:1;s:7:"level_0";b:1;s:17:"edit_others_pages";b:1;s:20:"edit_published_pages";b:1;s:13:"publish_pages";b:1;s:12:"delete_pages";b:1;s:19:"delete_others_pages";b:1;s:22:"delete_published_pages";b:1;s:12:"delete_posts";b:1;s:19:"delete_others_posts";b:1;s:22:"delete_published_posts";b:1;s:20:"delete_private_posts";b:1;s:18:"edit_private_posts";b:1;s:18:"read_private_posts";b:1;s:20:"delete_private_pages";b:1;s:18:"edit_private_pages";b:1;s:18:"read_private_pages";b:1;s:12:"delete_users";b:1;s:12:"create_users";b:1;s:17:"unfiltered_upload";b:1;s:14:"edit_dashboard";b:1;s:14:"update_plugins";b:1;s:14:"delete_plugins";b:1;s:15:"install_plugins";b:1;s:13:"update_themes";b:1;s:14:"install_themes";b:1;s:11:"update_core";b:1;s:10:"list_users";b:1;s:12:"remove_users";b:1;s:9:"add_users";b:1;s:13:"promote_users";b:1;s:18:"edit_theme_options";b:1;s:13:"delete_themes";b:1;s:6:"export";b:1;s:19:"access_masterslider";b:1;s:20:"publish_masterslider";b:1;s:19:"delete_masterslider";b:1;s:19:"create_masterslider";b:1;s:19:"export_masterslider";b:1;s:22:"duplicate_masterslider";b:1;}}s:6:"editor";a:2:{s:4:"name";s:6:"Editor";s:12:"capabilities";a:40:{s:17:"moderate_comments";b:1;s:17:"manage_categories";b:1;s:12:"manage_links";b:1;s:12:"upload_files";b:1;s:15:"unfiltered_html";b:1;s:10:"edit_posts";b:1;s:17:"edit_others_posts";b:1;s:20:"edit_published_posts";b:1;s:13:"publish_posts";b:1;s:10:"edit_pages";b:1;s:4:"read";b:1;s:7:"level_7";b:1;s:7:"level_6";b:1;s:7:"level_5";b:1;s:7:"level_4";b:1;s:7:"level_3";b:1;s:7:"level_2";b:1;s:7:"level_1";b:1;s:7:"level_0";b:1;s:17:"edit_others_pages";b:1;s:20:"edit_published_pages";b:1;s:13:"publish_pages";b:1;s:12:"delete_pages";b:1;s:19:"delete_others_pages";b:1;s:22:"delete_published_pages";b:1;s:12:"delete_posts";b:1;s:19:"delete_others_posts";b:1;s:22:"delete_published_posts";b:1;s:20:"delete_private_posts";b:1;s:18:"edit_private_posts";b:1;s:18:"read_private_posts";b:1;s:20:"delete_private_pages";b:1;s:18:"edit_private_pages";b:1;s:18:"read_private_pages";b:1;s:19:"access_masterslider";b:1;s:20:"publish_masterslider";b:1;s:19:"delete_masterslider";b:1;s:19:"create_masterslider";b:1;s:19:"export_masterslider";b:1;s:22:"duplicate_masterslider";b:1;}}s:6:"author";a:2:{s:4:"name";s:6:"Author";s:12:"capabilities";a:10:{s:12:"upload_files";b:1;s:10:"edit_posts";b:1;s:20:"edit_published_posts";b:1;s:13:"publish_posts";b:1;s:4:"read";b:1;s:7:"level_2";b:1;s:7:"level_1";b:1;s:7:"level_0";b:1;s:12:"delete_posts";b:1;s:22:"delete_published_posts";b:1;}}s:11:"contributor";a:2:{s:4:"name";s:11:"Contributor";s:12:"capabilities";a:5:{s:10:"edit_posts";b:1;s:4:"read";b:1;s:7:"level_1";b:1;s:7:"level_0";b:1;s:12:"delete_posts";b:1;}}s:10:"subscriber";a:2:{s:4:"name";s:10:"Subscriber";s:12:"capabilities";a:2:{s:4:"read";b:1;s:7:"level_0";b:1;}}}', 'yes'),
(90, 'widget_search', 'a:1:{s:12:"_multiwidget";i:1;}', 'yes'),
(91, 'widget_recent-posts', 'a:2:{i:2;a:2:{s:5:"title";s:0:"";s:6:"number";i:5;}s:12:"_multiwidget";i:1;}', 'yes'),
(92, 'widget_recent-comments', 'a:1:{s:12:"_multiwidget";i:1;}', 'yes'),
(93, 'widget_archives', 'a:1:{s:12:"_multiwidget";i:1;}', 'yes'),
(94, 'widget_meta', 'a:1:{s:12:"_multiwidget";i:1;}', 'yes'),
(95, 'sidebars_widgets', 'a:8:{s:19:"wp_inactive_widgets";a:0:{}s:13:"right_sidebar";a:3:{i:0;s:17:"subpages-widget-2";i:1;s:14:"recent-posts-2";i:2;s:12:"categories-2";}s:12:"left_sidebar";a:0:{}s:8:"footer_1";a:0:{}s:8:"footer_2";a:0:{}s:8:"footer_3";a:0:{}s:12:"tabs_sidebar";a:0:{}s:13:"array_version";i:3;}', 'yes'),
(97, 'cron', 'a:7:{i:1438001874;a:1:{s:26:"upgrader_scheduled_cleanup";a:1:{s:32:"d500441b538711fa00c3ef048e23faf3";a:2:{s:8:"schedule";b:0;s:4:"args";a:1:{i:0;i:51;}}}}i:1438020031;a:1:{s:30:"wp_scheduled_auto_draft_delete";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:3:{s:8:"schedule";s:5:"daily";s:4:"args";a:0:{}s:8:"interval";i:86400;}}}i:1438026889;a:2:{s:16:"wp_version_check";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:3:{s:8:"schedule";s:10:"twicedaily";s:4:"args";a:0:{}s:8:"interval";i:43200;}}s:17:"wp_update_plugins";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:3:{s:8:"schedule";s:10:"twicedaily";s:4:"args";a:0:{}s:8:"interval";i:43200;}}}i:1438026890;a:1:{s:16:"wp_update_themes";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:3:{s:8:"schedule";s:10:"twicedaily";s:4:"args";a:0:{}s:8:"interval";i:43200;}}}i:1438026927;a:1:{s:19:"wp_scheduled_delete";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:3:{s:8:"schedule";s:5:"daily";s:4:"args";a:0:{}s:8:"interval";i:86400;}}}i:1438026960;a:1:{s:20:"wp_maybe_auto_update";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:3:{s:8:"schedule";s:10:"twicedaily";s:4:"args";a:0:{}s:8:"interval";i:43200;}}}s:7:"version";i:2;}', 'yes'),
(108, '_transient_random_seed', '8b3fefd59107c9cbd9779501afab7744', 'yes'),
(109, '_site_transient_timeout_browser_ad43eed614c4eb778229f4155a1eb627', '1438199727', 'yes'),
(110, '_site_transient_browser_ad43eed614c4eb778229f4155a1eb627', 'a:9:{s:8:"platform";s:7:"Windows";s:4:"name";s:6:"Chrome";s:7:"version";s:13:"43.0.2357.134";s:10:"update_url";s:28:"http://www.google.com/chrome";s:7:"img_src";s:49:"http://s.wordpress.org/images/browsers/chrome.png";s:11:"img_src_ssl";s:48:"https://wordpress.org/images/browsers/chrome.png";s:15:"current_version";s:2:"18";s:7:"upgrade";b:0;s:8:"insecure";b:0;}', 'yes'),
(136, 'db_upgraded', '', 'yes'),
(139, 'auto_core_update_notified', 'a:4:{s:4:"type";s:4:"fail";s:5:"email";s:19:"lunardrik@gmail.com";s:7:"version";s:5:"4.2.3";s:9:"timestamp";i:1437975840;}', 'yes'),
(150, 'recently_activated', 'a:0:{}', 'yes'),
(169, '_transient_twentyfifteen_categories', '1', 'yes'),
(170, '_site_transient_update_themes', 'O:8:"stdClass":4:{s:12:"last_checked";i:1437994679;s:7:"checked";a:8:{s:8:"building";s:5:"2.4.2";s:11:"estateagent";s:5:"2.4.2";s:9:"homepress";s:5:"2.4.2";s:7:"myhouse";s:5:"2.4.2";s:9:"sweethome";s:5:"2.4.2";s:13:"twentyfifteen";s:3:"1.2";s:14:"twentyfourteen";s:3:"1.4";s:14:"twentythirteen";s:3:"1.5";}s:8:"response";a:0:{}s:12:"translations";a:0:{}}', 'yes'),
(171, 'theme_mods_twentyfifteen', 'a:1:{s:16:"sidebars_widgets";a:2:{s:4:"time";i:1437760990;s:4:"data";a:2:{s:19:"wp_inactive_widgets";a:0:{}s:9:"sidebar-1";a:6:{i:0;s:8:"search-2";i:1;s:14:"recent-posts-2";i:2;s:17:"recent-comments-2";i:3;s:10:"archives-2";i:4;s:12:"categories-2";i:5;s:6:"meta-2";}}}}', 'yes'),
(172, 'current_theme', 'Building', 'yes'),
(173, 'theme_mods_estateagent', 'a:2:{i:0;b:0;s:16:"sidebars_widgets";a:2:{s:4:"time";i:1437761190;s:4:"data";a:7:{s:19:"wp_inactive_widgets";a:0:{}s:13:"right_sidebar";a:6:{i:0;s:8:"search-2";i:1;s:14:"recent-posts-2";i:2;s:17:"recent-comments-2";i:3;s:10:"archives-2";i:4;s:12:"categories-2";i:5;s:6:"meta-2";}s:12:"left_sidebar";N;s:8:"footer_1";N;s:8:"footer_2";N;s:8:"footer_3";N;s:12:"tabs_sidebar";N;}}}', 'yes'),
(174, 'theme_switched', '', 'yes'),
(175, 'smt_hash', 'a438920ce392d3029e8ca3b076a307f4', 'yes'),
(176, 'main-menu', 'a:4:{s:6:"effect";s:15:"fade_slide_left";s:5:"speed";s:3:"200";s:5:"delay";s:3:"800";s:6:"arrows";s:1:"0";}', 'yes'),
(177, 'category_children', 'a:0:{}', 'yes'),
(178, 'widget_banners', 'a:2:{i:1;a:0:{}s:12:"_multiwidget";i:1;}', 'yes'),
(179, 'widget_comments', 'a:2:{i:1;a:0:{}s:12:"_multiwidget";i:1;}', 'yes'),
(180, 'widget_facebook', 'a:2:{i:1;a:0:{}s:12:"_multiwidget";i:1;}', 'yes'),
(181, 'widget_flickr', 'a:2:{i:1;a:0:{}s:12:"_multiwidget";i:1;}', 'yes'),
(182, 'widget_posts', 'a:2:{i:1;a:0:{}s:12:"_multiwidget";i:1;}', 'yes'),
(183, 'widget_social_profiles', 'a:2:{i:1;a:0:{}s:12:"_multiwidget";i:1;}', 'yes'),
(184, 'widget_tabs', 'a:2:{i:1;a:0:{}s:12:"_multiwidget";i:1;}', 'yes'),
(185, 'widget_videofeed', 'a:2:{i:1;a:0:{}s:12:"_multiwidget";i:1;}', 'yes'),
(186, 'widget_calendar', 'a:2:{i:1;a:0:{}s:12:"_multiwidget";i:1;}', 'yes'),
(187, 'widget_nav_menu', 'a:2:{i:1;a:0:{}s:12:"_multiwidget";i:1;}', 'yes'),
(188, 'widget_pages', 'a:2:{i:1;a:0:{}s:12:"_multiwidget";i:1;}', 'yes'),
(190, 'widget_tag_cloud', 'a:2:{i:1;a:0:{}s:12:"_multiwidget";i:1;}', 'yes'),
(192, 'theme_mods_myhouse', 'a:2:{i:0;b:0;s:16:"sidebars_widgets";a:2:{s:4:"time";i:1437763862;s:4:"data";a:7:{s:19:"wp_inactive_widgets";a:0:{}s:13:"right_sidebar";a:5:{i:0;s:8:"search-2";i:1;s:17:"subpages-widget-2";i:2;s:14:"recent-posts-2";i:3;s:12:"categories-2";i:4;s:6:"meta-2";}s:12:"left_sidebar";a:0:{}s:8:"footer_1";a:0:{}s:8:"footer_2";a:0:{}s:8:"footer_3";a:0:{}s:12:"tabs_sidebar";a:0:{}}}}', 'yes'),
(193, 'theme_switched_via_customizer', '', 'yes'),
(198, 'layout', 'a:12:{s:10:"pagelayout";s:1:"2";s:11:"dpagination";s:1:"1";s:7:"related";s:1:"1";s:10:"relatedcnt";s:1:"4";s:6:"colors";s:1:"1";s:8:"cuttxton";s:1:"1";s:6:"cuttxt";s:3:"800";s:8:"imgwidth";s:3:"663";s:9:"imgheight";s:3:"212";s:6:"imgpos";s:9:"alignleft";s:13:"footerwidgets";s:1:"1";s:10:"footertext";s:0:"";}', 'yes'),
(199, 'widget_subpages-widget', 'a:2:{i:2;a:5:{s:5:"title";s:0:"";s:17:"title_from_parent";i:1;s:10:"title_link";i:0;s:13:"deep_subpages";i:0;s:13:"nest_subpages";i:0;}s:12:"_multiwidget";i:1;}', 'yes'),
(204, 'theme_mods_building', 'a:1:{i:0;b:0;}', 'yes'),
(224, '_transient_timeout_plugin_slugs', '1438081082', 'no'),
(225, '_transient_plugin_slugs', 'a:7:{i:0;s:19:"akismet/akismet.php";i:1;s:41:"be-subpages-widget/be-subpages-widget.php";i:2;s:33:"eg-attachments/eg-attachments.php";i:3;s:37:"embed-google-map/embed_google_map.php";i:4;s:9:"hello.php";i:5;s:23:"slider-image/slider.php";i:6;s:31:"master-slider/master-slider.php";}', 'no'),
(229, '_site_transient_update_core', 'O:8:"stdClass":4:{s:7:"updates";a:2:{i:0;O:8:"stdClass":10:{s:8:"response";s:7:"upgrade";s:8:"download";s:59:"https://downloads.wordpress.org/release/wordpress-4.2.3.zip";s:6:"locale";s:5:"en_US";s:8:"packages";O:8:"stdClass":5:{s:4:"full";s:59:"https://downloads.wordpress.org/release/wordpress-4.2.3.zip";s:10:"no_content";s:70:"https://downloads.wordpress.org/release/wordpress-4.2.3-no-content.zip";s:11:"new_bundled";s:71:"https://downloads.wordpress.org/release/wordpress-4.2.3-new-bundled.zip";s:7:"partial";s:69:"https://downloads.wordpress.org/release/wordpress-4.2.3-partial-2.zip";s:8:"rollback";b:0;}s:7:"current";s:5:"4.2.3";s:7:"version";s:5:"4.2.3";s:11:"php_version";s:5:"5.2.4";s:13:"mysql_version";s:3:"5.0";s:11:"new_bundled";s:3:"4.1";s:15:"partial_version";s:5:"4.2.2";}i:1;O:8:"stdClass":12:{s:8:"response";s:10:"autoupdate";s:8:"download";s:59:"https://downloads.wordpress.org/release/wordpress-4.2.3.zip";s:6:"locale";s:5:"en_US";s:8:"packages";O:8:"stdClass":5:{s:4:"full";s:59:"https://downloads.wordpress.org/release/wordpress-4.2.3.zip";s:10:"no_content";s:70:"https://downloads.wordpress.org/release/wordpress-4.2.3-no-content.zip";s:11:"new_bundled";s:71:"https://downloads.wordpress.org/release/wordpress-4.2.3-new-bundled.zip";s:7:"partial";s:69:"https://downloads.wordpress.org/release/wordpress-4.2.3-partial-2.zip";s:8:"rollback";s:70:"https://downloads.wordpress.org/release/wordpress-4.2.3-rollback-2.zip";}s:7:"current";s:5:"4.2.3";s:7:"version";s:5:"4.2.3";s:11:"php_version";s:5:"5.2.4";s:13:"mysql_version";s:3:"5.0";s:11:"new_bundled";s:3:"4.1";s:15:"partial_version";s:5:"4.2.2";s:13:"support_email";s:26:"updatehelp42@wordpress.org";s:9:"new_files";s:0:"";}}s:12:"last_checked";i:1437994678;s:15:"version_checked";s:5:"4.2.2";s:12:"translations";a:0:{}}', 'yes'),
(230, 'can_compress_scripts', '1', 'yes'),
(233, 'slider', 'a:13:{s:6:"source";s:1:"1";s:13:"custom_slides";a:5:{i:1;a:4:{s:3:"img";s:67:"http://localhost/pre/wp-content/themes/building/images/slides/1.jpg";s:4:"link";s:20:"http://localhost/pre";s:3:"ttl";s:9:"Slide # 1";s:7:"content";s:115:"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts";}i:2;a:4:{s:3:"img";s:67:"http://localhost/pre/wp-content/themes/building/images/slides/2.jpg";s:4:"link";s:20:"http://localhost/pre";s:3:"ttl";s:9:"Slide # 2";s:7:"content";s:115:"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts";}i:3;a:4:{s:3:"img";s:67:"http://localhost/pre/wp-content/themes/building/images/slides/3.jpg";s:4:"link";s:20:"http://localhost/pre";s:3:"ttl";s:9:"Slide # 3";s:7:"content";s:115:"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts";}i:4;a:4:{s:3:"img";s:67:"http://localhost/pre/wp-content/themes/building/images/slides/4.jpg";s:4:"link";s:20:"http://localhost/pre";s:3:"ttl";s:9:"Slide # 4";s:7:"content";s:115:"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts";}i:5;a:4:{s:3:"img";s:67:"http://localhost/pre/wp-content/themes/building/images/slides/5.jpg";s:4:"link";s:20:"http://localhost/pre";s:3:"ttl";s:9:"Slide # 5";s:7:"content";s:115:"Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts";}}s:8:"category";a:3:{s:11:"numberposts";s:1:"5";s:8:"category";s:1:"0";s:7:"orderby";s:4:"date";}s:13:"showthumbnail";s:1:"1";s:8:"showtext";s:1:"1";s:7:"showttl";s:1:"1";s:9:"showhrefs";s:1:"1";s:6:"effect";s:4:"fade";s:5:"speed";s:4:"1000";s:7:"timeout";s:4:"3000";s:5:"pause";s:4:"1000";s:8:"homepage";s:1:"1";s:9:"innerpage";s:1:"0";}', 'yes'),
(245, 'auto_core_update_failed', 'a:6:{s:9:"attempted";s:5:"4.2.3";s:7:"current";s:5:"4.2.2";s:10:"error_code";s:15:"download_failed";s:10:"error_data";s:47:"Could not resolve host: downloads.wordpress.org";s:9:"timestamp";i:1437983801;s:5:"retry";b:1;}', 'yes'),
(246, '_transient_timeout_dash_4077549d03da2e451c8b5f002294ff51', '1438015602', 'no'),
(247, '_transient_dash_4077549d03da2e451c8b5f002294ff51', '<div class="rss-widget"><p><strong>RSS Error</strong>: WP HTTP Error: Could not resolve host: wordpress.org</p></div><div class="rss-widget"><p><strong>RSS Error</strong>: WP HTTP Error: Could not resolve host: planet.wordpress.org</p></div><div class="rss-widget"><ul></ul></div>', 'no'),
(249, 'EG-Attachments-Options', 'a:39:{s:8:"load_css";i:1;s:21:"uninstall_del_options";i:1;s:19:"uninstall_del_stats";i:0;s:17:"display_admin_bar";i:1;s:14:"tinymce_button";i:1;s:11:"use_metabox";i:0;s:14:"shortcode_auto";s:1:"0";s:24:"shortcode_auto_exclusive";s:1:"0";s:20:"shortcode_auto_where";a:2:{i:1;s:4:"post";i:2;s:4:"page";}s:20:"shortcode_auto_title";s:0:"";s:24:"shortcode_auto_title_tag";s:2:"h2";s:23:"shortcode_auto_template";s:6:"medium";s:23:"shortcode_auto_doc_type";s:8:"document";s:22:"shortcode_auto_orderby";s:5:"title";s:20:"shortcode_auto_order";s:3:"ASC";s:20:"shortcode_auto_limit";s:2:"-1";s:27:"shortcode_auto_default_opts";s:1:"0";s:12:"clicks_table";s:3:"1.1";s:18:"standard_templates";s:17:"38,39,40,41,42,43";s:12:"force_saveas";s:1:"0";s:17:"logged_users_only";s:1:"0";s:9:"login_url";s:0:"";s:12:"stats_enable";s:1:"0";s:16:"stats_ip_exclude";s:0:"";s:11:"purge_stats";s:2:"24";s:11:"date_format";s:0:"";s:15:"tags_assignment";i:0;s:8:"icon_set";s:5:"metro";s:9:"icon_path";s:0:"";s:8:"icon_url";s:0:"";s:10:"icon_image";s:4:"icon";s:4:"link";s:6:"direct";s:8:"nofollow";s:1:"0";s:12:"target_blank";s:1:"0";s:17:"exclude_thumbnail";s:1:"0";s:20:"legacy_custom_format";s:0:"";s:11:"clear_cache";b:0;s:12:"on_duplicate";i:1;s:7:"version";s:5:"2.1.3";}', 'yes'),
(265, '_site_transient_timeout_theme_roots', '1437996474', 'yes'),
(266, '_site_transient_theme_roots', 'a:8:{s:8:"building";s:7:"/themes";s:11:"estateagent";s:7:"/themes";s:9:"homepress";s:7:"/themes";s:7:"myhouse";s:7:"/themes";s:9:"sweethome";s:7:"/themes";s:13:"twentyfifteen";s:7:"/themes";s:14:"twentyfourteen";s:7:"/themes";s:14:"twentythirteen";s:7:"/themes";}', 'yes'),
(267, '_site_transient_update_plugins', 'O:8:"stdClass":1:{s:12:"last_checked";i:1437994681;}', 'yes'),
(268, 'masterslider_db_version', '1.03', 'yes'),
(269, 'masterslider_capabilities_added', '1', 'yes'),
(270, 'msp_general_setting', '', 'yes'),
(271, 'msp_advanced', '', 'yes'),
(272, 'upgrade_to_pro', '', 'yes'),
(273, 'masterslider_lite_plugin_version', '2.5.1', 'yes'),
(274, 'rewrite_rules', 'a:70:{s:47:"category/(.+?)/feed/(feed|rdf|rss|rss2|atom)/?$";s:52:"index.php?category_name=$matches[1]&feed=$matches[2]";s:42:"category/(.+?)/(feed|rdf|rss|rss2|atom)/?$";s:52:"index.php?category_name=$matches[1]&feed=$matches[2]";s:35:"category/(.+?)/page/?([0-9]{1,})/?$";s:53:"index.php?category_name=$matches[1]&paged=$matches[2]";s:17:"category/(.+?)/?$";s:35:"index.php?category_name=$matches[1]";s:44:"tag/([^/]+)/feed/(feed|rdf|rss|rss2|atom)/?$";s:42:"index.php?tag=$matches[1]&feed=$matches[2]";s:39:"tag/([^/]+)/(feed|rdf|rss|rss2|atom)/?$";s:42:"index.php?tag=$matches[1]&feed=$matches[2]";s:32:"tag/([^/]+)/page/?([0-9]{1,})/?$";s:43:"index.php?tag=$matches[1]&paged=$matches[2]";s:14:"tag/([^/]+)/?$";s:25:"index.php?tag=$matches[1]";s:45:"type/([^/]+)/feed/(feed|rdf|rss|rss2|atom)/?$";s:50:"index.php?post_format=$matches[1]&feed=$matches[2]";s:40:"type/([^/]+)/(feed|rdf|rss|rss2|atom)/?$";s:50:"index.php?post_format=$matches[1]&feed=$matches[2]";s:33:"type/([^/]+)/page/?([0-9]{1,})/?$";s:51:"index.php?post_format=$matches[1]&paged=$matches[2]";s:15:"type/([^/]+)/?$";s:33:"index.php?post_format=$matches[1]";s:48:".*wp-(atom|rdf|rss|rss2|feed|commentsrss2)\\.php$";s:18:"index.php?feed=old";s:20:".*wp-app\\.php(/.*)?$";s:19:"index.php?error=403";s:18:".*wp-register.php$";s:23:"index.php?register=true";s:32:"feed/(feed|rdf|rss|rss2|atom)/?$";s:27:"index.php?&feed=$matches[1]";s:27:"(feed|rdf|rss|rss2|atom)/?$";s:27:"index.php?&feed=$matches[1]";s:20:"page/?([0-9]{1,})/?$";s:28:"index.php?&paged=$matches[1]";s:41:"comments/feed/(feed|rdf|rss|rss2|atom)/?$";s:42:"index.php?&feed=$matches[1]&withcomments=1";s:36:"comments/(feed|rdf|rss|rss2|atom)/?$";s:42:"index.php?&feed=$matches[1]&withcomments=1";s:44:"search/(.+)/feed/(feed|rdf|rss|rss2|atom)/?$";s:40:"index.php?s=$matches[1]&feed=$matches[2]";s:39:"search/(.+)/(feed|rdf|rss|rss2|atom)/?$";s:40:"index.php?s=$matches[1]&feed=$matches[2]";s:32:"search/(.+)/page/?([0-9]{1,})/?$";s:41:"index.php?s=$matches[1]&paged=$matches[2]";s:14:"search/(.+)/?$";s:23:"index.php?s=$matches[1]";s:47:"author/([^/]+)/feed/(feed|rdf|rss|rss2|atom)/?$";s:50:"index.php?author_name=$matches[1]&feed=$matches[2]";s:42:"author/([^/]+)/(feed|rdf|rss|rss2|atom)/?$";s:50:"index.php?author_name=$matches[1]&feed=$matches[2]";s:35:"author/([^/]+)/page/?([0-9]{1,})/?$";s:51:"index.php?author_name=$matches[1]&paged=$matches[2]";s:17:"author/([^/]+)/?$";s:33:"index.php?author_name=$matches[1]";s:69:"([0-9]{4})/([0-9]{1,2})/([0-9]{1,2})/feed/(feed|rdf|rss|rss2|atom)/?$";s:80:"index.php?year=$matches[1]&monthnum=$matches[2]&day=$matches[3]&feed=$matches[4]";s:64:"([0-9]{4})/([0-9]{1,2})/([0-9]{1,2})/(feed|rdf|rss|rss2|atom)/?$";s:80:"index.php?year=$matches[1]&monthnum=$matches[2]&day=$matches[3]&feed=$matches[4]";s:57:"([0-9]{4})/([0-9]{1,2})/([0-9]{1,2})/page/?([0-9]{1,})/?$";s:81:"index.php?year=$matches[1]&monthnum=$matches[2]&day=$matches[3]&paged=$matches[4]";s:39:"([0-9]{4})/([0-9]{1,2})/([0-9]{1,2})/?$";s:63:"index.php?year=$matches[1]&monthnum=$matches[2]&day=$matches[3]";s:56:"([0-9]{4})/([0-9]{1,2})/feed/(feed|rdf|rss|rss2|atom)/?$";s:64:"index.php?year=$matches[1]&monthnum=$matches[2]&feed=$matches[3]";s:51:"([0-9]{4})/([0-9]{1,2})/(feed|rdf|rss|rss2|atom)/?$";s:64:"index.php?year=$matches[1]&monthnum=$matches[2]&feed=$matches[3]";s:44:"([0-9]{4})/([0-9]{1,2})/page/?([0-9]{1,})/?$";s:65:"index.php?year=$matches[1]&monthnum=$matches[2]&paged=$matches[3]";s:26:"([0-9]{4})/([0-9]{1,2})/?$";s:47:"index.php?year=$matches[1]&monthnum=$matches[2]";s:43:"([0-9]{4})/feed/(feed|rdf|rss|rss2|atom)/?$";s:43:"index.php?year=$matches[1]&feed=$matches[2]";s:38:"([0-9]{4})/(feed|rdf|rss|rss2|atom)/?$";s:43:"index.php?year=$matches[1]&feed=$matches[2]";s:31:"([0-9]{4})/page/?([0-9]{1,})/?$";s:44:"index.php?year=$matches[1]&paged=$matches[2]";s:13:"([0-9]{4})/?$";s:26:"index.php?year=$matches[1]";s:58:"[0-9]{4}/[0-9]{1,2}/[0-9]{1,2}/[^/]+/attachment/([^/]+)/?$";s:32:"index.php?attachment=$matches[1]";s:68:"[0-9]{4}/[0-9]{1,2}/[0-9]{1,2}/[^/]+/attachment/([^/]+)/trackback/?$";s:37:"index.php?attachment=$matches[1]&tb=1";s:88:"[0-9]{4}/[0-9]{1,2}/[0-9]{1,2}/[^/]+/attachment/([^/]+)/feed/(feed|rdf|rss|rss2|atom)/?$";s:49:"index.php?attachment=$matches[1]&feed=$matches[2]";s:83:"[0-9]{4}/[0-9]{1,2}/[0-9]{1,2}/[^/]+/attachment/([^/]+)/(feed|rdf|rss|rss2|atom)/?$";s:49:"index.php?attachment=$matches[1]&feed=$matches[2]";s:83:"[0-9]{4}/[0-9]{1,2}/[0-9]{1,2}/[^/]+/attachment/([^/]+)/comment-page-([0-9]{1,})/?$";s:50:"index.php?attachment=$matches[1]&cpage=$matches[2]";s:57:"([0-9]{4})/([0-9]{1,2})/([0-9]{1,2})/([^/]+)/trackback/?$";s:85:"index.php?year=$matches[1]&monthnum=$matches[2]&day=$matches[3]&name=$matches[4]&tb=1";s:77:"([0-9]{4})/([0-9]{1,2})/([0-9]{1,2})/([^/]+)/feed/(feed|rdf|rss|rss2|atom)/?$";s:97:"index.php?year=$matches[1]&monthnum=$matches[2]&day=$matches[3]&name=$matches[4]&feed=$matches[5]";s:72:"([0-9]{4})/([0-9]{1,2})/([0-9]{1,2})/([^/]+)/(feed|rdf|rss|rss2|atom)/?$";s:97:"index.php?year=$matches[1]&monthnum=$matches[2]&day=$matches[3]&name=$matches[4]&feed=$matches[5]";s:65:"([0-9]{4})/([0-9]{1,2})/([0-9]{1,2})/([^/]+)/page/?([0-9]{1,})/?$";s:98:"index.php?year=$matches[1]&monthnum=$matches[2]&day=$matches[3]&name=$matches[4]&paged=$matches[5]";s:72:"([0-9]{4})/([0-9]{1,2})/([0-9]{1,2})/([^/]+)/comment-page-([0-9]{1,})/?$";s:98:"index.php?year=$matches[1]&monthnum=$matches[2]&day=$matches[3]&name=$matches[4]&cpage=$matches[5]";s:57:"([0-9]{4})/([0-9]{1,2})/([0-9]{1,2})/([^/]+)(/[0-9]+)?/?$";s:97:"index.php?year=$matches[1]&monthnum=$matches[2]&day=$matches[3]&name=$matches[4]&page=$matches[5]";s:47:"[0-9]{4}/[0-9]{1,2}/[0-9]{1,2}/[^/]+/([^/]+)/?$";s:32:"index.php?attachment=$matches[1]";s:57:"[0-9]{4}/[0-9]{1,2}/[0-9]{1,2}/[^/]+/([^/]+)/trackback/?$";s:37:"index.php?attachment=$matches[1]&tb=1";s:77:"[0-9]{4}/[0-9]{1,2}/[0-9]{1,2}/[^/]+/([^/]+)/feed/(feed|rdf|rss|rss2|atom)/?$";s:49:"index.php?attachment=$matches[1]&feed=$matches[2]";s:72:"[0-9]{4}/[0-9]{1,2}/[0-9]{1,2}/[^/]+/([^/]+)/(feed|rdf|rss|rss2|atom)/?$";s:49:"index.php?attachment=$matches[1]&feed=$matches[2]";s:72:"[0-9]{4}/[0-9]{1,2}/[0-9]{1,2}/[^/]+/([^/]+)/comment-page-([0-9]{1,})/?$";s:50:"index.php?attachment=$matches[1]&cpage=$matches[2]";s:64:"([0-9]{4})/([0-9]{1,2})/([0-9]{1,2})/comment-page-([0-9]{1,})/?$";s:81:"index.php?year=$matches[1]&monthnum=$matches[2]&day=$matches[3]&cpage=$matches[4]";s:51:"([0-9]{4})/([0-9]{1,2})/comment-page-([0-9]{1,})/?$";s:65:"index.php?year=$matches[1]&monthnum=$matches[2]&cpage=$matches[3]";s:38:"([0-9]{4})/comment-page-([0-9]{1,})/?$";s:44:"index.php?year=$matches[1]&cpage=$matches[2]";s:27:".?.+?/attachment/([^/]+)/?$";s:32:"index.php?attachment=$matches[1]";s:37:".?.+?/attachment/([^/]+)/trackback/?$";s:37:"index.php?attachment=$matches[1]&tb=1";s:57:".?.+?/attachment/([^/]+)/feed/(feed|rdf|rss|rss2|atom)/?$";s:49:"index.php?attachment=$matches[1]&feed=$matches[2]";s:52:".?.+?/attachment/([^/]+)/(feed|rdf|rss|rss2|atom)/?$";s:49:"index.php?attachment=$matches[1]&feed=$matches[2]";s:52:".?.+?/attachment/([^/]+)/comment-page-([0-9]{1,})/?$";s:50:"index.php?attachment=$matches[1]&cpage=$matches[2]";s:20:"(.?.+?)/trackback/?$";s:35:"index.php?pagename=$matches[1]&tb=1";s:40:"(.?.+?)/feed/(feed|rdf|rss|rss2|atom)/?$";s:47:"index.php?pagename=$matches[1]&feed=$matches[2]";s:35:"(.?.+?)/(feed|rdf|rss|rss2|atom)/?$";s:47:"index.php?pagename=$matches[1]&feed=$matches[2]";s:28:"(.?.+?)/page/?([0-9]{1,})/?$";s:48:"index.php?pagename=$matches[1]&paged=$matches[2]";s:35:"(.?.+?)/comment-page-([0-9]{1,})/?$";s:48:"index.php?pagename=$matches[1]&cpage=$matches[2]";s:20:"(.?.+?)(/[0-9]+)?/?$";s:47:"index.php?pagename=$matches[1]&page=$matches[2]";}', 'yes');

-- --------------------------------------------------------

--
-- Table structure for table `wp_postmeta`
--

CREATE TABLE IF NOT EXISTS `wp_postmeta` (
  `meta_id` bigint(20) unsigned NOT NULL,
  `post_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `meta_key` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `meta_value` longtext COLLATE utf8mb4_unicode_ci
) ENGINE=InnoDB AUTO_INCREMENT=59 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `wp_postmeta`
--

INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES
(1, 2, '_wp_page_template', 'default'),
(12, 2, '_edit_lock', '1437761191:1'),
(13, 2, '_edit_last', '1'),
(14, 2, 'single_layout', '0'),
(15, 11, '_edit_last', '1'),
(16, 11, '_edit_lock', '1437761237:1'),
(17, 11, '_wp_page_template', 'default'),
(18, 11, 'single_layout', '0'),
(19, 13, '_edit_last', '1'),
(20, 13, '_edit_lock', '1437761779:1'),
(21, 13, '_wp_page_template', 'default'),
(22, 13, 'single_layout', '0'),
(23, 15, '_edit_last', '1'),
(24, 15, '_edit_lock', '1437762557:1'),
(25, 15, '_wp_page_template', 'default'),
(26, 15, 'single_layout', '0'),
(31, 20, '_edit_last', '1'),
(32, 20, '_edit_lock', '1437996339:1'),
(33, 20, '_wp_page_template', 'default'),
(34, 20, 'single_layout', '0'),
(35, 22, '_edit_last', '1'),
(36, 22, '_edit_lock', '1437762701:1'),
(37, 22, '_wp_page_template', 'default'),
(38, 22, 'single_layout', '0'),
(39, 24, '_edit_last', '1'),
(40, 24, '_edit_lock', '1437762812:1'),
(41, 24, '_wp_page_template', 'default'),
(42, 24, 'single_layout', '0'),
(43, 26, '_edit_last', '1'),
(44, 26, '_edit_lock', '1437991991:1'),
(45, 26, '_wp_page_template', 'default'),
(46, 26, 'single_layout', '0'),
(50, 34, '_edit_lock', '1437933140:1'),
(51, 35, '_edit_lock', '1437933262:1'),
(54, 44, '_wp_attached_file', '2015/07/Sample.pdf'),
(55, 46, '_wp_attached_file', '2015/07/Sample.xls'),
(56, 48, '_wp_attached_file', '2015/07/Sample.zip');

-- --------------------------------------------------------

--
-- Table structure for table `wp_posts`
--

CREATE TABLE IF NOT EXISTS `wp_posts` (
  `ID` bigint(20) unsigned NOT NULL,
  `post_author` bigint(20) unsigned NOT NULL DEFAULT '0',
  `post_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `post_date_gmt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `post_content` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `post_title` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `post_excerpt` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `post_status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'publish',
  `comment_status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'open',
  `ping_status` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'open',
  `post_password` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `post_name` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `to_ping` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `pinged` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `post_modified` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `post_modified_gmt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `post_content_filtered` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `post_parent` bigint(20) unsigned NOT NULL DEFAULT '0',
  `guid` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `menu_order` int(11) NOT NULL DEFAULT '0',
  `post_type` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'post',
  `post_mime_type` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `comment_count` bigint(20) NOT NULL DEFAULT '0'
) ENGINE=InnoDB AUTO_INCREMENT=54 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `wp_posts`
--

INSERT INTO `wp_posts` (`ID`, `post_author`, `post_date`, `post_date_gmt`, `post_content`, `post_title`, `post_excerpt`, `post_status`, `comment_status`, `ping_status`, `post_password`, `post_name`, `to_ping`, `pinged`, `post_modified`, `post_modified_gmt`, `post_content_filtered`, `post_parent`, `guid`, `menu_order`, `post_type`, `post_mime_type`, `comment_count`) VALUES
(1, 1, '2015-07-22 19:54:48', '2015-07-22 19:54:48', 'Welcome to WordPress. This is your first post. Edit or delete it, then start blogging!', 'Hello world!', '', 'publish', 'open', 'open', '', 'hello-world', '', '', '2015-07-22 19:54:48', '2015-07-22 19:54:48', '', 0, 'http://localhost/pre/?p=1', 0, 'post', '', 1),
(2, 1, '2015-07-22 19:54:48', '2015-07-22 19:54:48', 'This is an example page. It''s different from a blog post because it will stay in one place and will show up in your site navigation (in most themes). Most people start with an About page that introduces them to potential site visitors. It might say something like this:\r\n<blockquote>Hi there! I''m a bike messenger by day, aspiring actor by night, and this is my blog. I live in Los Angeles, have a great dog named Jack, and I like piÃ±a coladas. (And gettin'' caught in the rain.)</blockquote>\r\n...or something like this:\r\n<blockquote>The XYZ Doohickey Company was founded in 1971, and has been providing quality doohickeys to the public ever since. Located in Gotham City, XYZ employs over 2,000 people and does all kinds of awesome things for the Gotham community.</blockquote>\r\nAs a new WordPress user, you should go to <a href="http://localhost/pre/wp-admin/">your dashboard</a> to delete this page and create new pages for your content. Have fun!', 'Dự án the Villa Park', '', 'publish', 'open', 'open', '', 'sample-page', '', '', '2015-07-24 18:08:50', '2015-07-24 18:08:50', '', 0, 'http://localhost/pre/?page_id=2', 0, 'page', '', 0),
(3, 1, '2015-07-22 19:55:27', '0000-00-00 00:00:00', '', 'Auto Draft', '', 'auto-draft', 'open', 'open', '', '', '', '', '2015-07-22 19:55:27', '0000-00-00 00:00:00', '', 0, 'http://localhost/pre/?p=3', 0, 'post', '', 0),
(4, 1, '2015-07-24 18:00:31', '0000-00-00 00:00:00', '', 'Auto Draft', '', 'auto-draft', 'open', 'open', '', '', '', '', '2015-07-24 18:00:31', '0000-00-00 00:00:00', '', 0, 'http://localhost/pre/?page_id=4', 0, 'page', '', 0),
(10, 1, '2015-07-24 18:08:50', '2015-07-24 18:08:50', 'This is an example page. It''s different from a blog post because it will stay in one place and will show up in your site navigation (in most themes). Most people start with an About page that introduces them to potential site visitors. It might say something like this:\r\n<blockquote>Hi there! I''m a bike messenger by day, aspiring actor by night, and this is my blog. I live in Los Angeles, have a great dog named Jack, and I like piÃ±a coladas. (And gettin'' caught in the rain.)</blockquote>\r\n...or something like this:\r\n<blockquote>The XYZ Doohickey Company was founded in 1971, and has been providing quality doohickeys to the public ever since. Located in Gotham City, XYZ employs over 2,000 people and does all kinds of awesome things for the Gotham community.</blockquote>\r\nAs a new WordPress user, you should go to <a href="http://localhost/pre/wp-admin/">your dashboard</a> to delete this page and create new pages for your content. Have fun!', 'Dự án the Villa Park', '', 'inherit', 'open', 'open', '', '2-revision-v1', '', '', '2015-07-24 18:08:50', '2015-07-24 18:08:50', '', 2, 'http://localhost/pre/2015/07/24/2-revision-v1/', 0, 'revision', '', 0),
(11, 1, '2015-07-24 18:09:37', '2015-07-24 18:09:37', 'Thông tin dự án', 'Thông tin', '', 'publish', 'open', 'open', '', 'thong-tin', '', '', '2015-07-24 18:09:37', '2015-07-24 18:09:37', '', 2, 'http://localhost/pre/?page_id=11', 0, 'page', '', 0),
(12, 1, '2015-07-24 18:09:37', '2015-07-24 18:09:37', 'Thông tin dự án', 'Thông tin', '', 'inherit', 'open', 'open', '', '11-revision-v1', '', '', '2015-07-24 18:09:37', '2015-07-24 18:09:37', '', 11, 'http://localhost/pre/2015/07/24/11-revision-v1/', 0, 'revision', '', 0),
(13, 1, '2015-07-24 18:10:59', '2015-07-24 18:10:59', 'Thông tin về vị trí\r\n\r\n{google_map}10.801351,106.803349{/google_map}\r\n\r\n&nbsp;', 'Vị trí - bản đồ', '', 'publish', 'open', 'open', '', 'vi-tri-ban-do', '', '', '2015-07-24 18:15:00', '2015-07-24 18:15:00', '', 2, 'http://localhost/pre/?page_id=13', 0, 'page', '', 0),
(14, 1, '2015-07-24 18:10:59', '2015-07-24 18:10:59', 'Thông tin về vị trí', 'Vị trí - bản đồ', '', 'inherit', 'open', 'open', '', '13-revision-v1', '', '', '2015-07-24 18:10:59', '2015-07-24 18:10:59', '', 13, 'http://localhost/pre/2015/07/24/13-revision-v1/', 0, 'revision', '', 0),
(15, 1, '2015-07-24 18:11:21', '2015-07-24 18:11:21', 'Thông tin giá nhà đất', 'Bảng giá', '', 'publish', 'open', 'open', '', 'bang-gia', '', '', '2015-07-24 18:11:21', '2015-07-24 18:11:21', '', 2, 'http://localhost/pre/?page_id=15', 0, 'page', '', 0),
(16, 1, '2015-07-24 18:11:21', '2015-07-24 18:11:21', 'Thông tin giá nhà đất', 'Bảng giá', '', 'inherit', 'open', 'open', '', '15-revision-v1', '', '', '2015-07-24 18:11:21', '2015-07-24 18:11:21', '', 15, 'http://localhost/pre/2015/07/24/15-revision-v1/', 0, 'revision', '', 0),
(18, 1, '2015-07-24 18:15:00', '2015-07-24 18:15:00', 'Thông tin vị trí\r\n\r\n{google_map}10.801351,106.803349{/google_map}\r\n\r\n&nbsp;', 'Vị trí - bản đồ', '', 'inherit', 'open', 'open', '', '13-revision-v1', '', '', '2015-07-24 18:15:00', '2015-07-24 18:15:00', '', 13, 'http://localhost/pre/2015/07/24/13-revision-v1/', 0, 'revision', '', 0),
(20, 1, '2015-07-24 18:33:22', '2015-07-24 18:33:22', '[masterslider id="1"]\r\n<h2 class="ser_title">Tổng quan dự án</h2>\r\n<div class="project_desc_f">\r\n\r\nMột sự kết hợp tinh tế giữa không gian xanh thiên nhiên và những tiện ích nghỉ dưỡng hiện đại. Mỗi căn biệt thự có thiết kế không gian sân vườn riêng biệt nằm xen lẫn với các khu công viên nội khu giúp đem lại cho bạn cảm giác tận hưởng tối đa nhưng không kém phần riêng tư khi gia đình sum vầy bên nhau.\r\n\r\nTọa lạc trên đường Bưng Ông Thoàn, quận 9, TP HCM, gần kề cao tốc Long Thành - Dầu Giây và đường Vành đai trong, <strong>Villa Park </strong>bao gồm 248 căn biệt thự đơn lập, song lập và liên lập trên tổng diện tích 11,2ha với đầy đủ các tiện ích cho cuộc sống tiện nghi, hiện đại <strong>mang đậm phong cách sống của Mỹ</strong>. Dự án đã bàn giao nhà đợt một với hơn <strong>60% biệt thự đã có chủ nhân sở hữu,</strong> <strong>50% cư dân đã chuyển vào sinh sống </strong>cùng toàn bộ tiện ích đã đi vào hoạt động.\r\n<p style="text-align: center;"><img src="http://www.mik.vn/vnt_upload/File/04_2015/Gate_2.jpg" alt="Gate_2" /></p>\r\n<p style="text-align: center;"><strong>Tổng diện tích:</strong> 11,2 hecta |  <strong>Tổng số biệt thự:</strong> 248 căn</p>\r\n<strong>Tiện ích: </strong>Hồ bơi, phòng tập Gym, sân tenis, sân Golf mini, 8 công viên nội khu, đường dạo bộ ven sông, khu vui chơi thiếu nhi, khu BBQ, phòng cộng đồng…\r\n\r\n</div>', 'Dự án Carillon 2', '', 'publish', 'open', 'open', '', 'du-an-carillon-2', '', '', '2015-07-27 11:27:40', '2015-07-27 11:27:40', '', 0, 'http://localhost/pre/?page_id=20', 0, 'page', '', 0),
(21, 1, '2015-07-24 18:33:22', '2015-07-24 18:33:22', 'Thông tin về dự án căn hộ Carillon 2', 'Dự án Carillon 2', '', 'inherit', 'open', 'open', '', '20-revision-v1', '', '', '2015-07-24 18:33:22', '2015-07-24 18:33:22', '', 20, 'http://localhost/pre/2015/07/24/20-revision-v1/', 0, 'revision', '', 0),
(22, 1, '2015-07-24 18:34:02', '2015-07-24 18:34:02', 'Thông tin chi tiết dự án căn hộ Carillon 2', 'Thông tin', '', 'publish', 'open', 'open', '', 'thong-tin', '', '', '2015-07-24 18:34:02', '2015-07-24 18:34:02', '', 20, 'http://localhost/pre/?page_id=22', 0, 'page', '', 0),
(23, 1, '2015-07-24 18:34:02', '2015-07-24 18:34:02', 'Thông tin chi tiết dự án căn hộ Carillon 2', 'Thông tin', '', 'inherit', 'open', 'open', '', '22-revision-v1', '', '', '2015-07-24 18:34:02', '2015-07-24 18:34:02', '', 22, 'http://localhost/pre/2015/07/24/22-revision-v1/', 0, 'revision', '', 0),
(24, 1, '2015-07-24 18:35:53', '2015-07-24 18:35:53', 'Thông tin vị trí dự án căn hộ Carillon 2\r\n\r\n{google_map}10.7755355,106.6341077{/google_map}', 'Vị trí - bản đồ', '', 'publish', 'open', 'open', '', 'vi-tri-ban-do', '', '', '2015-07-24 18:35:53', '2015-07-24 18:35:53', '', 20, 'http://localhost/pre/?page_id=24', 0, 'page', '', 0),
(25, 1, '2015-07-24 18:35:53', '2015-07-24 18:35:53', 'Thông tin vị trí dự án căn hộ Carillon 2\r\n\r\n{google_map}10.7755355,106.6341077{/google_map}', 'Vị trí - bản đồ', '', 'inherit', 'open', 'open', '', '24-revision-v1', '', '', '2015-07-24 18:35:53', '2015-07-24 18:35:53', '', 24, 'http://localhost/pre/2015/07/24/24-revision-v1/', 0, 'revision', '', 0),
(26, 1, '2015-07-24 18:36:19', '2015-07-24 18:36:19', 'Bảng giá chi tiết dự án căn hộ Carillon 2\r\n\r\n[attachments template=medium force_saveas=1]', 'Bảng giá', '', 'publish', 'open', 'open', '', 'bang-gia', '', '', '2015-07-27 09:09:52', '2015-07-27 09:09:52', '', 20, 'http://localhost/pre/?page_id=26', 0, 'page', '', 0),
(27, 1, '2015-07-24 18:36:19', '2015-07-24 18:36:19', 'Báº£ng giÃ¡ chi tiáº¿t cÄƒn há»™ Carillon 2', 'Bảng giá', '', 'inherit', 'open', 'open', '', '26-revision-v1', '', '', '2015-07-24 18:36:19', '2015-07-24 18:36:19', '', 26, 'http://localhost/pre/2015/07/24/26-revision-v1/', 0, 'revision', '', 0),
(30, 1, '2015-07-24 18:38:20', '2015-07-24 18:38:20', 'Bảng giá chi tiết dự án căn hộ Carillon 2\r\n\r\n<a href="http://localhost/pre/wp-content/uploads/2015/07/911_Research_topics_for_2013.xlsx">Bảng giá dự án căn hộ Carillon 2</a>', 'Bảng giá', '', 'inherit', 'open', 'open', '', '26-revision-v1', '', '', '2015-07-24 18:38:20', '2015-07-24 18:38:20', '', 26, 'http://localhost/pre/2015/07/24/26-revision-v1/', 0, 'revision', '', 0),
(31, 2, '2015-07-24 18:41:32', '0000-00-00 00:00:00', '', 'Auto Draft', '', 'auto-draft', 'open', 'open', '', '', '', '', '2015-07-24 18:41:32', '0000-00-00 00:00:00', '', 0, 'http://localhost/pre/?p=31', 0, 'post', '', 0),
(32, 1, '2015-07-26 17:24:30', '0000-00-00 00:00:00', '', 'Auto Draft', '', 'auto-draft', 'open', 'open', '', '', '', '', '2015-07-26 17:24:30', '0000-00-00 00:00:00', '', 0, 'http://localhost/pre/?p=32', 0, 'post', '', 0),
(34, 1, '2015-07-26 17:52:04', '0000-00-00 00:00:00', '', 'Auto Draft', '', 'auto-draft', 'open', 'open', '', '', '', '', '2015-07-26 17:52:04', '0000-00-00 00:00:00', '', 0, 'http://localhost/pre/?p=34', 0, 'post', '', 0),
(35, 1, '2015-07-26 17:52:42', '0000-00-00 00:00:00', '', 'Auto Draft', '', 'auto-draft', 'open', 'open', '', '', '', '', '2015-07-26 17:52:42', '0000-00-00 00:00:00', '', 0, 'http://localhost/pre/?page_id=35', 0, 'page', '', 0),
(36, 1, '2015-07-26 17:56:22', '2015-07-26 17:56:22', '[huge_it_slider id="1"]\r\n\r\nThông tin dự án căn hộ Carillon 2', 'Dự án Carillon 2', '', 'inherit', 'open', 'open', '', '20-revision-v1', '', '', '2015-07-26 17:56:22', '2015-07-26 17:56:22', '', 20, 'http://localhost/pre/2015/07/26/20-revision-v1/', 0, 'revision', '', 0),
(38, 1, '2015-07-27 04:47:37', '2015-07-27 04:47:37', '[before][/before]\r\n[loop]<dl class="attachments attachments-large"><dt class="icon">\r\n	<a title="%TITLE%" href="%URL%" %NOFOLLOW%>\r\n		%ICON-48x48%\r\n	</a>\r\n</dt>\r\n<dd class="caption">\r\n	%SHOWLOCK%<strong>%TITLE_LABEL%</strong>: <a title="%TITLE%" href="%URL%" %NOFOLLOW%>%TITLE%</a> (%COUNTER% %COUNTER_LABEL%)\r\n	<br/>\r\n	<strong>%CAPTION_LABEL%</strong>: %CAPTION%\r\n	<br/>\r\n	<strong>%FILENAME_LABEL%</strong>: %FILENAME%\r\n	<br/>\r\n	<strong>%FILESIZE_LABEL%</strong>: %FILESIZE%\r\n</dd>\r\n</dl>[/loop][after][/after]', 'Large', 'List with details, and big icon', 'publish', 'closed', 'closed', '', 'large', '', '', '2015-07-27 04:47:37', '2015-07-27 04:47:37', '', 0, 'http://localhost/pre/2015/07/27/large/', 0, 'egatmpl', '', 0),
(39, 1, '2015-07-27 04:47:37', '2015-07-27 04:47:37', '[before]<ul>[/before]\r\n[loop]<li  class="attachments-large">\r\n	<strong>%TITLE_LABEL%</strong>:	<a title="%TITLE%" href="%URL%" %NOFOLLOW%>%TITLE%</a>\r\n	<br/>\r\n	<strong>%CAPTION_LABEL%</strong>: %CAPTION%\r\n	<br/>\r\n	<strong>%FILENAME_LABEL%</strong>:  <a title="%TITLE%" href="%URL%" %NOFOLLOW%>%FILENAME%</a>\r\n	<br/>\r\n	<strong>%FILESIZE_LABEL%</strong>: %FILESIZE%\r\n</li>[/loop]\r\n[after]</ul>[/after]', 'Large list', 'Large list of attachments without icon', 'publish', 'closed', 'closed', '', 'large-list', '', '', '2015-07-27 04:47:37', '2015-07-27 04:47:37', '', 0, 'http://localhost/pre/2015/07/27/large-list/', 0, 'egatmpl', '', 0),
(40, 1, '2015-07-27 04:47:37', '2015-07-27 04:47:37', '[before]<style>\r\n.attachments img {\r\n  margin: 0px !important;\r\n}\r\ndl.attachments-medium {\r\n  border: 1px solid lightskyblue;\r\n  padding: 0px;\r\n}\r\ndt.icon {\r\n  line-height: 10px;\r\n  margin: -1px;\r\n}\r\ndd.caption {\r\n  line-height: 15px;\r\n  padding-top: 5px !important;\r\n}\r\ndd.caption div {\r\n  display: inline-block;\r\n  overflow: hidden;\r\n  white-space: nowrap;\r\n  text-overflow: ellipsis;\r\n}\r\n</style>[/before][loop]<dl class="attachments attachments-medium">\r\n<dt class="icon">\r\n	<a title="%TITLE%" href="%URL%" %NOFOLLOW%>\r\n		%ICON-64x64%\r\n	</a>\r\n</dt>\r\n<dd class="caption">\r\n	<div><strong>%FILENAME_LABEL%</strong> : <a title="%TITLE%" href="%URL%" %NOFOLLOW%>%FILENAME%</a></div>\r\n	<br>\r\n	<div><strong>%CAPTION_LABEL%</strong> : %CAPTION%</div>\r\n	<br>\r\n	<div><strong>%FILESIZE_LABEL%</strong> : %FILESIZE%</div>\r\n</dd>\r\n</dl>[/loop][after]<script type="text/javascript">\r\nvar colorThief = new ColorThief(),\r\n    atms = jQuery("dl.attachments-medium");\r\n\r\natms.each(function(i, o) {\r\n    c = colorThief.getColor(jQuery(o).find("img")[0]);\r\n    jQuery(o).css({ borderColor: ''rgb(''+c.join('','')+'')'' });\r\n})\r\n</script>[/after]', 'Medium', 'List with details, and medium size icon', 'publish', 'closed', 'closed', '', 'medium', '', '', '2015-07-27 09:05:56', '2015-07-27 09:05:56', '', 0, 'http://localhost/pre/2015/07/27/medium/', 0, 'egatmpl', '', 0),
(41, 1, '2015-07-27 04:47:37', '2015-07-27 04:47:37', '[before]<ul>[/before]\r\n[loop]<li class="attachments attachments-medium">\r\n	<strong>%FILENAME_LABEL%</strong> : <a title="%TITLE%" href="%URL%" %NOFOLLOW%>%FILENAME%</a> (%FILESIZE%)\r\n	<br>\r\n	<strong>%CAPTION_LABEL%</strong> : %CAPTION%\r\n</li>[/loop]\r\n[after]</ul>[/after]', 'Medium list', 'Medium list of attachments without icon', 'publish', 'closed', 'closed', '', 'medium-list', '', '', '2015-07-27 04:47:37', '2015-07-27 04:47:37', '', 0, 'http://localhost/pre/2015/07/27/medium-list/', 0, 'egatmpl', '', 0),
(42, 1, '2015-07-27 04:47:37', '2015-07-27 04:47:37', '[before][/before]\r\n[loop]<dl class="attachments attachments-small">\r\n	<dt class="icon">\r\n		<a title="%TITLE%" href="%URL%" %NOFOLLOW%>\r\n			%ICON-16x16%\r\n		</a>\r\n	</dt>\r\n	<dd class="caption">\r\n		<a title="%TITLE%" href="%URL%" %NOFOLLOW%>%FILENAME%</a> (%FILESIZE%)\r\n	</dd>\r\n</dl>[/loop]\r\n[after][/after]', 'Small', 'List with details, and small size icon', 'publish', 'closed', 'closed', '', 'small', '', '', '2015-07-27 04:47:37', '2015-07-27 04:47:37', '', 0, 'http://localhost/pre/2015/07/27/small/', 0, 'egatmpl', '', 0),
(43, 1, '2015-07-27 04:47:37', '2015-07-27 04:47:37', '[before]<ul>[/before]\r\n[loop]<li class="attachments attachments-small">\r\n	<a title="%TITLE%" href="%URL%" %NOFOLLOW%>%FILENAME%</a> (%FILESIZE%)\r\n</li>[/loop]\r\n[after]</ul>[/after]', 'Small list', 'Small list of attachments without icon', 'publish', 'closed', 'closed', '', 'small-list', '', '', '2015-07-27 04:47:37', '2015-07-27 04:47:37', '', 0, 'http://localhost/pre/2015/07/27/small-list/', 0, 'egatmpl', '', 0),
(44, 1, '2015-07-27 05:01:55', '2015-07-27 05:01:55', 'Bảng giá chương trình bán hàng The Villa Park', 'Sample', 'Chương trình bán hàng The Villa Park', 'inherit', 'open', 'open', '', 'sample', '', '', '2015-07-27 05:03:11', '2015-07-27 05:03:11', '', 26, 'http://localhost/pre/wp-content/uploads/2015/07/Sample.pdf', 0, 'attachment', 'application/pdf', 0),
(45, 1, '2015-07-27 05:04:41', '2015-07-27 05:04:41', 'Bảng giá chi tiết dự án căn hộ Carillon 2\r\n\r\n[attachments template=medium force_saveas=1]', 'Bảng giá', '', 'inherit', 'open', 'open', '', '26-revision-v1', '', '', '2015-07-27 05:04:41', '2015-07-27 05:04:41', '', 26, 'http://localhost/pre/2015/07/27/26-revision-v1/', 0, 'revision', '', 0),
(46, 1, '2015-07-27 05:05:23', '2015-07-27 05:05:23', 'Bảng giá chi tiết căn hộ Carillon 2', 'Sample', 'Bảng giá căn hộ Carillon 2', 'inherit', 'open', 'open', '', 'sample-2', '', '', '2015-07-27 08:53:54', '2015-07-27 08:53:54', '', 26, 'http://localhost/pre/wp-content/uploads/2015/07/Sample.xls', 0, 'attachment', 'application/vnd.ms-excel', 0),
(48, 1, '2015-07-27 09:07:24', '2015-07-27 09:07:24', 'Thông tin liên hệ', 'Sample', 'Thông tin liên hệ', 'inherit', 'open', 'open', '', 'sample-3', '', '', '2015-07-27 09:08:13', '2015-07-27 09:08:13', '', 26, 'http://localhost/pre/wp-content/uploads/2015/07/Sample.zip', 0, 'attachment', 'application/zip', 0),
(49, 1, '2015-07-27 09:08:22', '2015-07-27 09:08:22', 'Bảng giá chi tiết dự án căn hộ Carillon 2\r\n\r\n[attachments template=medium force_saveas=1]', 'Bảng giá', '', 'inherit', 'open', 'open', '', '26-autosave-v1', '', '', '2015-07-27 09:08:22', '2015-07-27 09:08:22', '', 26, 'http://localhost/pre/2015/07/27/26-autosave-v1/', 0, 'revision', '', 0),
(50, 1, '2015-07-27 10:16:07', '2015-07-27 10:16:07', '[huge_it_slider id="1"]\r\n<h2 class="ser_title">Tổng quan dự án</h2>\r\n<div class="project_desc_f">\r\n\r\nMột sự kết hợp tinh tế giữa không gian xanh thiên nhiên và những tiện ích nghỉ dưỡng hiện đại. Mỗi căn biệt thự có thiết kế không gian sân vườn riêng biệt nằm xen lẫn với các khu công viên nội khu giúp đem lại cho bạn cảm giác tận hưởng tối đa nhưng không kém phần riêng tư khi gia đình sum vầy bên nhau.\r\n\r\nTọa lạc trên đường Bưng Ông Thoàn, quận 9, TP HCM, gần kề cao tốc Long Thành - Dầu Giây và đường Vành đai trong, <strong>Villa Park </strong>bao gồm 248 căn biệt thự đơn lập, song lập và liên lập trên tổng diện tích 11,2ha với đầy đủ các tiện ích cho cuộc sống tiện nghi, hiện đại <strong>mang đậm phong cách sống của Mỹ</strong>. Dự án đã bàn giao nhà đợt một với hơn <strong>60% biệt thự đã có chủ nhân sở hữu,</strong> <strong>50% cư dân đã chuyển vào sinh sống </strong>cùng toàn bộ tiện ích đã đi vào hoạt động.\r\n<p style="text-align: center;"></p>\r\n<p style="text-align: center;"><img src="http://www.mik.vn/vnt_upload/File/04_2015/Gate_2.jpg" alt="Gate_2" /></p>\r\n<p style="text-align: center;"><strong>Tổng diện tích:</strong> 11,2 hecta |  <strong>Tổng số biệt thự:</strong> 248 căn</p>\r\n<strong>Tiện ích: </strong>Hồ bơi, phòng tập Gym, sân tenis, sân Golf mini, 8 công viên nội khu, đường dạo bộ ven sông, khu vui chơi thiếu nhi, khu BBQ, phòng cộng đồng…\r\n\r\n</div>', 'Dự án Carillon 2', '', 'inherit', 'open', 'open', '', '20-revision-v1', '', '', '2015-07-27 10:16:07', '2015-07-27 10:16:07', '', 20, 'http://localhost/pre/2015/07/27/20-revision-v1/', 0, 'revision', '', 0),
(52, 1, '2015-07-27 11:27:26', '2015-07-27 11:27:26', '[masterslider id="1"]\n<h2 class="ser_title">Tổng quan dự án</h2>\n<div class="project_desc_f">\n\nMột sự kết hợp tinh tế giữa không gian xanh thiên nhiên và những tiện ích nghỉ dưỡng hiện đại. Mỗi căn biệt thự có thiết kế không gian sân vườn riêng biệt nằm xen lẫn với các khu công viên nội khu giúp đem lại cho bạn cảm giác tận hưởng tối đa nhưng không kém phần riêng tư khi gia đình sum vầy bên nhau.\n\nTọa lạc trên đường Bưng Ông Thoàn, quận 9, TP HCM, gần kề cao tốc Long Thành - Dầu Giây và đường Vành đai trong, <strong>Villa Park </strong>bao gồm 248 căn biệt thự đơn lập, song lập và liên lập trên tổng diện tích 11,2ha với đầy đủ các tiện ích cho cuộc sống tiện nghi, hiện đại <strong>mang đậm phong cách sống của Mỹ</strong>. Dự án đã bàn giao nhà đợt một với hơn <strong>60% biệt thự đã có chủ nhân sở hữu,</strong> <strong>50% cư dân đã chuyển vào sinh sống </strong>cùng toàn bộ tiện ích đã đi vào hoạt động.\n<p style="text-align: center;"><img src="http://www.mik.vn/vnt_upload/File/04_2015/Gate_2.jpg" alt="Gate_2" /></p>\n<p style="text-align: center;"><strong>Tổng diện tích:</strong> 11,2 hecta |  <strong>Tổng số biệt thự:</strong> 248 căn</p>\n<strong>Tiện ích: </strong>Hồ bơi, phòng tập Gym, sân tenis, sân Golf mini, 8 công viên nội khu, đường dạo bộ ven sông, khu vui chơi thiếu nhi, khu BBQ, phòng cộng đồng…\n\n</div>', 'Dự án Carillon 2', '', 'inherit', 'open', 'open', '', '20-autosave-v1', '', '', '2015-07-27 11:27:26', '2015-07-27 11:27:26', '', 20, 'http://localhost/pre/2015/07/27/20-autosave-v1/', 0, 'revision', '', 0),
(53, 1, '2015-07-27 11:27:40', '2015-07-27 11:27:40', '[masterslider id="1"]\r\n<h2 class="ser_title">Tổng quan dự án</h2>\r\n<div class="project_desc_f">\r\n\r\nMột sự kết hợp tinh tế giữa không gian xanh thiên nhiên và những tiện ích nghỉ dưỡng hiện đại. Mỗi căn biệt thự có thiết kế không gian sân vườn riêng biệt nằm xen lẫn với các khu công viên nội khu giúp đem lại cho bạn cảm giác tận hưởng tối đa nhưng không kém phần riêng tư khi gia đình sum vầy bên nhau.\r\n\r\nTọa lạc trên đường Bưng Ông Thoàn, quận 9, TP HCM, gần kề cao tốc Long Thành - Dầu Giây và đường Vành đai trong, <strong>Villa Park </strong>bao gồm 248 căn biệt thự đơn lập, song lập và liên lập trên tổng diện tích 11,2ha với đầy đủ các tiện ích cho cuộc sống tiện nghi, hiện đại <strong>mang đậm phong cách sống của Mỹ</strong>. Dự án đã bàn giao nhà đợt một với hơn <strong>60% biệt thự đã có chủ nhân sở hữu,</strong> <strong>50% cư dân đã chuyển vào sinh sống </strong>cùng toàn bộ tiện ích đã đi vào hoạt động.\r\n<p style="text-align: center;"><img src="http://www.mik.vn/vnt_upload/File/04_2015/Gate_2.jpg" alt="Gate_2" /></p>\r\n<p style="text-align: center;"><strong>Tổng diện tích:</strong> 11,2 hecta |  <strong>Tổng số biệt thự:</strong> 248 căn</p>\r\n<strong>Tiện ích: </strong>Hồ bơi, phòng tập Gym, sân tenis, sân Golf mini, 8 công viên nội khu, đường dạo bộ ven sông, khu vui chơi thiếu nhi, khu BBQ, phòng cộng đồng…\r\n\r\n</div>', 'Dự án Carillon 2', '', 'inherit', 'open', 'open', '', '20-revision-v1', '', '', '2015-07-27 11:27:40', '2015-07-27 11:27:40', '', 20, 'http://localhost/pre/2015/07/27/20-revision-v1/', 0, 'revision', '', 0);

-- --------------------------------------------------------

--
-- Table structure for table `wp_terms`
--

CREATE TABLE IF NOT EXISTS `wp_terms` (
  `term_id` bigint(20) unsigned NOT NULL,
  `name` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `slug` varchar(200) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `term_group` bigint(10) NOT NULL DEFAULT '0'
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `wp_terms`
--

INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES
(1, 'Uncategorized', 'uncategorized', 0);

-- --------------------------------------------------------

--
-- Table structure for table `wp_term_relationships`
--

CREATE TABLE IF NOT EXISTS `wp_term_relationships` (
  `object_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `term_taxonomy_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `term_order` int(11) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `wp_term_relationships`
--

INSERT INTO `wp_term_relationships` (`object_id`, `term_taxonomy_id`, `term_order`) VALUES
(1, 1, 0);

-- --------------------------------------------------------

--
-- Table structure for table `wp_term_taxonomy`
--

CREATE TABLE IF NOT EXISTS `wp_term_taxonomy` (
  `term_taxonomy_id` bigint(20) unsigned NOT NULL,
  `term_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `taxonomy` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `description` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `parent` bigint(20) unsigned NOT NULL DEFAULT '0',
  `count` bigint(20) NOT NULL DEFAULT '0'
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `wp_term_taxonomy`
--

INSERT INTO `wp_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES
(1, 1, 'category', '', 0, 1);

-- --------------------------------------------------------

--
-- Table structure for table `wp_usermeta`
--

CREATE TABLE IF NOT EXISTS `wp_usermeta` (
  `umeta_id` bigint(20) unsigned NOT NULL,
  `user_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `meta_key` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `meta_value` longtext COLLATE utf8mb4_unicode_ci
) ENGINE=InnoDB AUTO_INCREMENT=32 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `wp_usermeta`
--

INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES
(1, 1, 'nickname', 'admin'),
(2, 1, 'first_name', ''),
(3, 1, 'last_name', ''),
(4, 1, 'description', ''),
(5, 1, 'rich_editing', 'true'),
(6, 1, 'comment_shortcuts', 'false'),
(7, 1, 'admin_color', 'fresh'),
(8, 1, 'use_ssl', '0'),
(9, 1, 'show_admin_bar_front', 'true'),
(10, 1, 'wp_capabilities', 'a:1:{s:13:"administrator";b:1;}'),
(11, 1, 'wp_user_level', '10'),
(12, 1, 'dismissed_wp_pointers', 'wp360_locks,wp390_widgets,wp410_dfw,ega_tinymce_button,ega_template_keywords,ega_templates'),
(13, 1, 'show_welcome_panel', '1'),
(14, 1, 'session_tokens', 'a:2:{s:64:"155b7b50cb2b6bae05b7c6181a4f22088e31a95ec81b9d535bb2adcc638c8166";a:4:{s:10:"expiration";i:1439134594;s:2:"ip";s:3:"::1";s:2:"ua";s:109:"Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.134 Safari/537.36";s:5:"login";i:1437924994;}s:64:"a46924a4f6a18234f8befdb4204e57a38c60b562545e4f0a8526408a4b40030e";a:4:{s:10:"expiration";i:1438145199;s:2:"ip";s:3:"::1";s:2:"ua";s:109:"Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.134 Safari/537.36";s:5:"login";i:1437972399;}}'),
(15, 1, 'wp_dashboard_quick_press_last_post_id', '3'),
(16, 1, 'wp_user-settings', 'editor=tinymce&libraryContent=browse&urlbutton=post&mfold=o'),
(17, 1, 'wp_user-settings-time', '1437972394'),
(18, 2, 'nickname', 'manager'),
(19, 2, 'first_name', ''),
(20, 2, 'last_name', ''),
(21, 2, 'description', ''),
(22, 2, 'rich_editing', 'true'),
(23, 2, 'comment_shortcuts', 'false'),
(24, 2, 'admin_color', 'fresh'),
(25, 2, 'use_ssl', '0'),
(26, 2, 'show_admin_bar_front', 'true'),
(27, 2, 'wp_capabilities', 'a:1:{s:6:"editor";b:1;}'),
(28, 2, 'wp_user_level', '7'),
(29, 2, 'dismissed_wp_pointers', 'wp360_locks,wp390_widgets'),
(31, 2, 'wp_dashboard_quick_press_last_post_id', '31');

-- --------------------------------------------------------

--
-- Table structure for table `wp_users`
--

CREATE TABLE IF NOT EXISTS `wp_users` (
  `ID` bigint(20) unsigned NOT NULL,
  `user_login` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `user_pass` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `user_nicename` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `user_email` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `user_url` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `user_registered` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `user_activation_key` varchar(60) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `user_status` int(11) NOT NULL DEFAULT '0',
  `display_name` varchar(250) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT ''
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `wp_users`
--

INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES
(1, 'admin', '$P$B4Ms00hGEgcqQI1bwtm470L2ftRIxg0', 'admin', 'lunardrik@gmail.com', '', '2015-07-22 19:54:47', '', 0, 'admin'),
(2, 'manager', '$P$BWjH5B1Ua2ZnTBI72zQiDTjEtC159g.', 'manager', 'lunar.drik@gmail.com', '', '2015-07-24 18:41:11', '', 0, 'manager');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `wp_commentmeta`
--
ALTER TABLE `wp_commentmeta`
  ADD PRIMARY KEY (`meta_id`), ADD KEY `comment_id` (`comment_id`), ADD KEY `meta_key` (`meta_key`(191));

--
-- Indexes for table `wp_comments`
--
ALTER TABLE `wp_comments`
  ADD PRIMARY KEY (`comment_ID`), ADD KEY `comment_post_ID` (`comment_post_ID`), ADD KEY `comment_approved_date_gmt` (`comment_approved`,`comment_date_gmt`), ADD KEY `comment_date_gmt` (`comment_date_gmt`), ADD KEY `comment_parent` (`comment_parent`), ADD KEY `comment_author_email` (`comment_author_email`(10));

--
-- Indexes for table `wp_eg_attachments_clicks`
--
ALTER TABLE `wp_eg_attachments_clicks`
  ADD PRIMARY KEY (`click_date`,`post_id`,`attach_id`), ADD KEY `click_date` (`click_date`), ADD KEY `click_id` (`click_id`);

--
-- Indexes for table `wp_huge_itslider_images`
--
ALTER TABLE `wp_huge_itslider_images`
  ADD PRIMARY KEY (`id`), ADD UNIQUE KEY `id` (`id`);

--
-- Indexes for table `wp_huge_itslider_params`
--
ALTER TABLE `wp_huge_itslider_params`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `wp_huge_itslider_sliders`
--
ALTER TABLE `wp_huge_itslider_sliders`
  ADD PRIMARY KEY (`id`), ADD UNIQUE KEY `id` (`id`);

--
-- Indexes for table `wp_links`
--
ALTER TABLE `wp_links`
  ADD PRIMARY KEY (`link_id`), ADD KEY `link_visible` (`link_visible`);

--
-- Indexes for table `wp_masterslider_options`
--
ALTER TABLE `wp_masterslider_options`
  ADD PRIMARY KEY (`ID`), ADD UNIQUE KEY `option_name` (`option_name`);

--
-- Indexes for table `wp_masterslider_sliders`
--
ALTER TABLE `wp_masterslider_sliders`
  ADD PRIMARY KEY (`ID`), ADD KEY `date_created` (`date_created`);

--
-- Indexes for table `wp_options`
--
ALTER TABLE `wp_options`
  ADD PRIMARY KEY (`option_id`), ADD UNIQUE KEY `option_name` (`option_name`);

--
-- Indexes for table `wp_postmeta`
--
ALTER TABLE `wp_postmeta`
  ADD PRIMARY KEY (`meta_id`), ADD KEY `post_id` (`post_id`), ADD KEY `meta_key` (`meta_key`(191));

--
-- Indexes for table `wp_posts`
--
ALTER TABLE `wp_posts`
  ADD PRIMARY KEY (`ID`), ADD KEY `post_name` (`post_name`(191)), ADD KEY `type_status_date` (`post_type`,`post_status`,`post_date`,`ID`), ADD KEY `post_parent` (`post_parent`), ADD KEY `post_author` (`post_author`);

--
-- Indexes for table `wp_terms`
--
ALTER TABLE `wp_terms`
  ADD PRIMARY KEY (`term_id`), ADD KEY `slug` (`slug`(191)), ADD KEY `name` (`name`(191));

--
-- Indexes for table `wp_term_relationships`
--
ALTER TABLE `wp_term_relationships`
  ADD PRIMARY KEY (`object_id`,`term_taxonomy_id`), ADD KEY `term_taxonomy_id` (`term_taxonomy_id`);

--
-- Indexes for table `wp_term_taxonomy`
--
ALTER TABLE `wp_term_taxonomy`
  ADD PRIMARY KEY (`term_taxonomy_id`), ADD UNIQUE KEY `term_id_taxonomy` (`term_id`,`taxonomy`), ADD KEY `taxonomy` (`taxonomy`);

--
-- Indexes for table `wp_usermeta`
--
ALTER TABLE `wp_usermeta`
  ADD PRIMARY KEY (`umeta_id`), ADD KEY `user_id` (`user_id`), ADD KEY `meta_key` (`meta_key`(191));

--
-- Indexes for table `wp_users`
--
ALTER TABLE `wp_users`
  ADD PRIMARY KEY (`ID`), ADD KEY `user_login_key` (`user_login`), ADD KEY `user_nicename` (`user_nicename`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `wp_commentmeta`
--
ALTER TABLE `wp_commentmeta`
  MODIFY `meta_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT;
--
-- AUTO_INCREMENT for table `wp_comments`
--
ALTER TABLE `wp_comments`
  MODIFY `comment_ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=2;
--
-- AUTO_INCREMENT for table `wp_eg_attachments_clicks`
--
ALTER TABLE `wp_eg_attachments_clicks`
  MODIFY `click_id` bigint(20) NOT NULL AUTO_INCREMENT;
--
-- AUTO_INCREMENT for table `wp_huge_itslider_images`
--
ALTER TABLE `wp_huge_itslider_images`
  MODIFY `id` int(11) unsigned NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=5;
--
-- AUTO_INCREMENT for table `wp_huge_itslider_params`
--
ALTER TABLE `wp_huge_itslider_params`
  MODIFY `id` int(11) unsigned NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=127;
--
-- AUTO_INCREMENT for table `wp_huge_itslider_sliders`
--
ALTER TABLE `wp_huge_itslider_sliders`
  MODIFY `id` int(11) unsigned NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=3;
--
-- AUTO_INCREMENT for table `wp_links`
--
ALTER TABLE `wp_links`
  MODIFY `link_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT;
--
-- AUTO_INCREMENT for table `wp_masterslider_options`
--
ALTER TABLE `wp_masterslider_options`
  MODIFY `ID` smallint(5) unsigned NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=2;
--
-- AUTO_INCREMENT for table `wp_masterslider_sliders`
--
ALTER TABLE `wp_masterslider_sliders`
  MODIFY `ID` mediumint(8) unsigned NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=2;
--
-- AUTO_INCREMENT for table `wp_options`
--
ALTER TABLE `wp_options`
  MODIFY `option_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=275;
--
-- AUTO_INCREMENT for table `wp_postmeta`
--
ALTER TABLE `wp_postmeta`
  MODIFY `meta_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=59;
--
-- AUTO_INCREMENT for table `wp_posts`
--
ALTER TABLE `wp_posts`
  MODIFY `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=54;
--
-- AUTO_INCREMENT for table `wp_terms`
--
ALTER TABLE `wp_terms`
  MODIFY `term_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=2;
--
-- AUTO_INCREMENT for table `wp_term_taxonomy`
--
ALTER TABLE `wp_term_taxonomy`
  MODIFY `term_taxonomy_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=2;
--
-- AUTO_INCREMENT for table `wp_usermeta`
--
ALTER TABLE `wp_usermeta`
  MODIFY `umeta_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=32;
--
-- AUTO_INCREMENT for table `wp_users`
--
ALTER TABLE `wp_users`
  MODIFY `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=3;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
